### ISSUE TITLE
PGP / SMIME encrpyted / signed mail handling

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#1081]
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/268308

**Comment by freescout-helpdesk** [comment]
Should signing be configured on a per mailbox basis? or same keys/certs for all mailboxes?

**Comment by freescout-helpdesk** [comment]
Is signing needed only for emails sent to customers or also for email notifications to users?

**Comment by Servery** [comment]
> Should signing be configured on a per mailbox basis? or same keys/certs for all mailboxes?

There are no wildcard S/MIME certificates so it will be per mailbox basis. For testing/private usage you'll get a S/MIME for free at: https://www.actalis.it/en/certificates-for-secure-electronic-mail.aspx

> Is signing needed only for emails sent to customers or also for email notifications to users?

Signing is most important for mails send to customers.

**Comment by XtomtomX** [comment]
It would be nice if PGP is supported and not "only" SMIME encrypted mails. For us it's also mainly used to send sensitive data in an encrypted way to customers.

**Comment by freescout-helpdesk** [comment]
The following modes are possible:
- Sign
- Sign & Encrypt
- Encrypt only

Is "Encrypt only" mode needed?

**Comment by freescout-helpdesk** [comment]
Will it be a problem if all outgoing emails (to customers and users) from the mailbox will be signed/encrypted?

**Comment by XtomtomX** [comment]
It would be nice to have the possibility to activate it per use case e.g. encrypt only to customers but send as plain text to users or encrypt to users & customers. 

If the Ticketsystem runs in the same secure network as the mailserver it would be not necessary to have a user encryption (and there would need to be a pgp key for all the users in place if the ticket is encrypted and sent to the users).

**Comment by Servery** [comment]
> Will it be a problem if all outgoing emails (to customers and users) from the mailbox will be signed/encrypted?

All signed would be great, but all encrypted can be a problem in my opinion. Encrypting should be activated per customer. (I do not need encrypting anyways.)

**Comment by freescout-helpdesk** [comment]
> It would be nice if PGP is supported and not "only" SMIME encrypted mails. For us it's also mainly used to send sensitive data in an encrypted way to customers.

Till now we could not find any working OpenPGP library for SwiftMailer. There are two ones, but they are not working:

https://github.com/Mailgarant/switfmailer-openpgp
https://github.com/NightJar/SwiftSigner-CryptGPG

**Comment by XtomtomX** [comment]
It seems that they [1] are also referring to the same resource which you already shared.
[1] https://github.com/swiftmailer/swiftmailer/issues/861#issuecomment-273027074

**Comment by freescout-helpdesk** [comment]
Beta version of the module: https://freescout.net/module/mail-signing/

Try SMIME and PGP and let us know if it works for you.

**Comment by Servery** [comment]
I can not install the module because gnupg PHP extension is not installed on my shared hosting provider. Is it possible to allow installation of the module and using S/MIME without installed gnupg PHP extension?

**Comment by freescout-helpdesk** [comment]
Fixed. Just clear the cache and try again.

**Comment by Servery** [comment]
Signing with S/MIME works great. 👌

**Comment by XtomtomX** [comment]
Hi,
first i want to thank you for the nice implementation of this plugin!

I've tested the PGP part of the Extension. Here is my two cents:

### Setup:
- Activation of the Module
- Installation of the required extension (on Debian 10 it was `apt-get install php7.3-gnupg`)
- Key creation: For me with Debian 10 as a base system it was not possible to create a key without a passphrase. I just created the keys with Kleopatra and copied it over to the Freescout installation (with setting the rights for the www-data group to the specific pgp keys which are located in the home directory).

### Usage:
Signing of mails works perfectly fine.
Signing & encryption:
- As suggested in the module description `gpg --gen-key` creates an keyring into which the certificates need to be imported (in this case the sending certificate of the mailbox mail in Freescout)
- If a PGP public key is contained in the keyring this key will automatically used to encrypt outgoing mail with the public key.
- If encryption is activated on the specific mailbox there is atm the requirement that all customer need to provide a pgp key. Otherwise it is not possible to send mails to them ("Unable to find an active key to encrypt for example@example.com, try importing keys first") -> This is resolved by importing the key into the keyring.
- if a mail comes in encrypted, then the agent needs to download the attachment which contains the encrypted message and decrypt it with a local tool to view the mail body.

### Suggestions
My suggestions for future work would be to add a button to activate encryption (or deactivate) in the create or reply view (on a per customer lvl). This would enable the agents to send answers to people which did not provided an pgp key. In addition it would be nice if signed incoming mails automatically get imported into the keyring. At the moment a agent needs to connect with ssh to the server and import the key manually (just correct me please if i missed something). The possibility to upload pgp keys of customers over the webinterface would also be a nice addition to the module. Maybe it would be good to have an indicator in the create/reply view which tells the agent if there is already a pgp key in the keyring. A normal agent is in general not able to look into the logfiles or check if there is someting in the outgoing dropdown option listed.

**Comment by freescout-helpdesk** [comment]
Thanks for the report. We will see what can be done.

**Comment by im-fabian** [comment]
Hi! 

Signing with S/MIME works like a charm. But I wonder what's the state with encryption?

1. I think it's important that incoming encrypted mails are decrypted automaticly. Because when sending out signed mails some clients may respond with encrypted mails.
2. Some kind of keymanagment is needed for customer keys. Like: If the customer sends in an signed or encrypted&signed mail his public key should be automaticly stored and used if encryption of a future message is needed.

As this is a very important feature to me, I appreciate this module and the work you put in it a lot!

**Comment by Gernomaly** [comment]
Is there still being work done on this issue, because even though it is closed it is not fixed?

**Comment by freescout-helpdesk** [comment]
> Is there still being work done on this issue, because even though it is closed it is not fixed?

No much.

**Comment by Gernomaly** [comment]
Is it possible to have a look at that again, because we would really like this to be implemented

**Comment by mchuc** [comment]
Sorry, but I don't understand something about PGP keys
I created a passwordless key and imported it in the container
docker exec -it myIMAGE /bin/bash
gpg --import mycert.asc

I am unable to sign with the key because the system does not see it

why path to the path of keys then

/home/xxxxxuser//.gnupg


what user the system is running on to import this key just for him

**Comment by mchuc** [comment]
Uff...
Step 0a. create GPG cert without password (Kleopatra)
Step 0b. export it as asc and open in notepad (and copy)


Step 1. log in into Your docker image:
docker exec -it myIMAGE /bin/bash

Step 2. 
# cd /root/
# nano cert.asc

step 3. copy and paste cert from step 0b

step 4.
#mkdir -p /www/XXX/.gnupg
#export GNUPGHOME=/home/XXX/.gnupg
#gpg --import cert.asc

#cd /home

chown -R nginx.www-data ./XXX
chmod -R gu+rx ./XXX


step 5 👍 
in plugin page set path: /home/XXX/.gnupg

and give e-mail address, as in cert, created in step 0a

**Comment by nooblag** [comment]
Thank you for implementing encryption :)

> My suggestions for future work would be to 
> 1. add a button to activate encryption (or deactivate) in the create or reply view (on a per customer lvl). This would enable the agents to send answers to people which did not provided an pgp key. 
> 2. it would be nice if signed incoming mails automatically get imported into the keyring. At the moment a agent needs to connect with ssh to the server and import the key manually [...]
> 3. The possibility to upload pgp keys of customers over the webinterface [...] A normal agent is in general not able to look into the logfiles or check if there is someting in the outgoing dropdown option listed.

:100: yes please for all these 3 suggestions!!!

At the moment, the module is not completely usable for normal users. Especially part 2, where server administrators have to SSH in and _manually_ add each customer's key to `gpg` keyring! That seems like the first thing to implement, then add the other two.

Thanks!
