### ISSUE TITLE
Knowledgebase shorten domain

### ISSUE THREAD

**Issue by datznoah** [freescout-helpdesk/freescout#1097]
I was looking into the knowledgebase plugin and wondered if there was a way to have a shortened domain for it, example:

https://help.example.com

and not

https://help.example.com/hc/12345

**Comment by freescout-helpdesk** [comment]
Unfortunately not.

**Comment by expressIndustries** [comment]
Agree.  This should be simple and short!  Just /help or whatever.

**Comment by datznoah** [comment]
> Agree.  This should be simple and short!  Just /help or whatever.  
> 
> 

Or the admin area could be moved to /admin or something, both are better than the current solution in my opinion

**Comment by freescout-helpdesk** [comment]
Unfortunately, no plans for now.

**Comment by expressIndustries** [comment]
Closed?  This is a pretty important feature.  It makes the support page
look fairly low-quality by not being able to properly name it.  What is the
idea behind having this less-than-desirable URL structure?




On March 17, 2021 at 1:51:44 AM, FreeScout ***@***.***) wrote:

Unfortunately, no plans for now.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/freescout-helpdesk/freescout/issues/1097#issuecomment-800909578>,
or unsubscribe
