### ISSUE TITLE
Chat Module - Enduser portal Contact Form Widget

### ISSUE THREAD

**Issue by webtyphoon** [freescout-helpdesk/freescout#1102]
Hi there,

nice addition to all the mods. What if I have embedded the contact form widget on my page. Will there be 2 buttons or is this transformed into one button and when click on it, it will open up into 2 more buttons to choose from 1. contact 2. chat?

When not - is it possible to have both running and give the chat thing a "business hours" / "offline" function, so either the business hours or the stuff is offline, its just showing the contact widget?

Optimization:
Also what have mentioned in other posts about the contact widget:

- Possible way to disable the upload function and additional to the upload a way to restrict certain file-formats.

Usability:
Don't hide the fields for personal information behind the 3 dots -> You have to remember that not all ppl on internet are firm with this kind of extracting more information. One of our target groups are ppl over 50 and don't know what this mini-images (yes, they don't see them or don't know what they are) are for.

Beside of that all - thx for this great tool.
Steve

**Comment by freescout-helpdesk** [comment]
With time.

**Comment by distresscode** [comment]
Here are some things I'd like to see added to the chat module in addition to what is mentioned above.

- Ability to customize the agent name based on each mailbox so that one user can have different aliases for each mailbox.
- On a separate but related note, the user's name currently has First & Last name fields that are "REQUIRED". Please make those optional. Use case example: I can set the First Name to STAFF and leave the Last name blank.
- Agent status (online/offline) to toggle chat widget on/off or ability to set business hours to control chat status automatically.
- Chat box displaying "live chat" when online and "send us a message" when all agents are offline.
- Alternatively, have the chat box be hidden when no agents are online.

Thanks!

**Comment by qsvch** [comment]
A good implementation of the chat for Freescout, thank you for that. For us, the module is unfortunately only of limited use because:

This would require the box with "Live chat" (when online), and "Send us a message" (when everyone is offline).

More than a widget cannot be inserted into the website this way. The caht would therefore have to be part of the end-user portal or at least integrated.

**Comment by freescout-helpdesk** [comment]
Chat Operating Hours added in the Chat Module v1.0.1

**Comment by pmhtuk** [comment]
Agree with above, would be good to have a 'search kb articles' first before offering live chat (office hours) or contact form (after hours)

**Comment by freescout-helpdesk** [comment]
Knowledge Base widget added in the Knowledge Base Module v1.0.7: https://freescout.net/module/knowledge-base/
