### ISSUE TITLE
Show conversation number in subject line of e-mails sent to customers

### ISSUE THREAD

**Issue by neosonic2** [freescout-helpdesk/freescout#1146]
Hello,

This may have been tackled somewhere else but after searching through the Github issues I haven't been able to find any mention of this request.

We are running the latest version of Freescout and although we have only been using it for a few days, we've found it to be a really great system that is lacking one small feature. Is it possible to include the ticket/conversation number in the subject line of replies or new conversation e-mails sent to customers? I realize this number is displayed inside Freescout, but it is not included in the subject line of outgoing e-mails even though most other support solutions include the ticket/conversation ID/number in the subject line.

An example subject that represents this might be: "[Ticket #123456] Test Ticket"

Thanks for any insight provided.

**Comment by cf39** [comment]
Is there a specific reason you want to do this? Most ticket systems need it because it is used to match the email to an existing ticket. In Freescout this is not necessary so you can have clean subjects.

I don't know It is possible to easily add the number to the subject (there isn't a setting for this) but the number is available as a variable that can be added to the signature or the body of the mail (the latter requiring the saved replies module).

**Comment by neosonic2** [comment]
I think it would just be a nice feature to have, i.e. as a toggle in settings or something. I know Freescout doesn't use it as a way to match the customer's e-mail to an existing ticket, but most customers are probably used to seeing ticket numbers in subject lines of e-mails they receive from support systems so it would be nice if Freescout could offer a similar behavior to match other solutions.

**Comment by freescout-helpdesk** [comment]
Feel free to add to https://freescout.net/request-feature/ or implement as custom module. We will close it for now.
