### ISSUE TITLE
Loop:: Unable to process your update

### ISSUE THREAD

**Issue by operations999** [freescout-helpdesk/freescout#1403]
We are getting weird issue of loop.
We created mailbox but problem is when some user email it create a loop with message

Your email update couldn't be processed

If you are trying to update a conversation, remember you must respond from the same email address that's on your account. To send your update, please try again and send from your account email address (the email you login with).

**Comment by freescout-helpdesk** [comment]
We have no idea what can be the reason.

**Comment by Phalebote** [comment]
Hi Everyone,

I believe I have found what the issue is and how to resolve it. Shout out to GreenShot for the sweet screenshot app and editor used to make the _amazing_ image below.

**Background:**
- This issue started happening immediately after I migrated my business Google Workspace e-mail hosting to my on-prem Synology NAS running MailPlus Server. 
- I have a Support@mydomain.com account that was hosted on Google Workspace and connected to FreeScout as the mailbox.
- The Support account and my individual business account (we will call it UserA@mydomain.com) mailboxes were migrated to the Synology MailPlus Server and configured as active mailboxes.
- I have a third account in Google Workspace, we will call it UserB@mydomain.com, for an old employee that is no longer with me. I did not migrate this account's e-mail data to MailPlus nor did I make it an active mailbox on the MailPlus Server.

Enough background...

**The Issue:**
Almost immediately after reconfiguring my FreeScout server's mailbox connection settings to my new MailPlus Server I started getting the same recurring email/ticket from my FreeScout server as described originally above in this Issue. I searched high and low for a quick Google fix but came up empty as my mailbox, on the other hand, filled up with email after email from FreeScout.

**The Discovery:**

After trying various things to fix the issue, I ate dinner, and came back to it with fresh eyes. I finally looked at the logs again hoping to find something I did not see before. Here is what I found:
<img width="1233" alt="FreeScout_SpamUrself_Fix" src="https://github.com/freescout-helpdesk/freescout/assets/29687476/c94f0c5c-443c-4b5c-a896-fd6742dbdb4d">

If we look at lines timestamped 17:02:05 and 17:02:06 in the screenshot above we see the "Type" as "User replied from wrong email address." related to UserB (recall from above in Background that this user was not set up with an active mailbox anymore). UserB also had a FreeScout account when they worked for me. This FreeScout account had UserB@mydomain.com associated with it.

When a new ticket was entered UserB@mydomain.com was getting sent the notification via email, but I think my mail server is e-mailing back FreeScout _from a different email address than UserB@mydomain.com_ the email address is no longer in service. Therefore, "User replied from wrong email address."

**The Fix:**
To fix this, I blew away UserB's account from FreeScout. Immediately after that, FreeScout stopped emailing incessantly and everything was happy again!

Thanks.
Phalebote
