### ISSUE TITLE
email sorting

### ISSUE THREAD

**Issue by cicoasm** [freescout-helpdesk/freescout#1537]
Hello,
I want to sort the emails by "ID Desc" or by date.
I want the user to see older emails first.

How can I do?

Thanks, freescout is great.

**Comment by freescout-helpdesk** [comment]
Not possible for now. Maybe will be implemented in the future.

**Comment by grrinch** [comment]
I second this one. 

If there was an option to sort by the date the message was received in the mailbox, not when it was downloaded would be great.

For example, instead of "Waiting Since", there could be just another column with "Received" date (of the message, not a downloaded ticket) and have it sortable. 

This is specifically useful when you're connecting an old mailbox and need the old conversations inside Freescout.

**Comment by MarcoWel** [comment]
+1

**Comment by freescout-helpdesk** [comment]
This feature has already been implemented. It's possible to sort conversations by Subject, Number and Date.
