### ISSUE TITLE
How to Translate fields of the Custom User Portal

### ISSUE THREAD

**Issue by alichakery** [freescout-helpdesk/freescout#1904]
Hello,

Would you please help me to translate the fields of the user portal? The main language of my FS is English however, one of our inboxes should be in German.

![Screen Shot 2022-04-08 at 21 24 24](https://user-images.githubusercontent.com/12240218/162510972-91223bd5-ccfc-4318-a669-021cab6e3e11.png)

Also it would be great if you add an inline contact us box in addition to the floating widget.

Thank you ...

**Comment by freescout-helpdesk** [comment]
End-User portal is always displayed in the language set in Manage > Settings. For now there is no way to set the language on a per mailbox basis.

**Comment by DanielBendersky** [comment]
Hi, I set the language in Manage > Settings to **Spanish**.  But when I go to the End User Portal, I see 4 words that are not translated. Also, I tried to search in the translation module, but there is no End user option for translation. Please help me in order to translate those words in any way. Thanks...

![2022-07-21 at 18](https://user-images.githubusercontent.com/84030633/180324300-7c62ea67-7850-4930-9184-4a01fad39eb8.png)
.

**Comment by olpo24** [comment]
@freescout-helpdesk 
> End-User portal is always displayed in the language set in Manage > Settings. For now there is no way to set the language on a per mailbox basis.

Please make this possiible. Or with an language switcher in the menu bar, as with the knowlede base module.
