### ISSUE TITLE
How do I take the auto-assigning of tickets away when replying to an email?

### ISSUE THREAD

**Issue by dmannow** [freescout-helpdesk/freescout#2153]
Our FreeScout system will automatically assign a ticket to one of us when simply replying to the ticket. This can cause problems if say a tech is out of the office and we are simply replying to state that "Tech will be gone until December 31st". When we do this it auto-assigns  the ticket to whoever replied - we would like this feature disabled and want to be able to manually assign the tickets. Is this doable? We only want the portion that assigns tickets based off of a reply removed.

**Comment by ilyakonovalenko** [comment]
You can configure assignee per mailbox (Default Assignee).

**Comment by dmannow** [comment]
But we use a shared mailbox  ***@***.***> ***@***.*** to receive the emails. If one of us replies to it, we are automatically assigned the ticket.

 

Devon Ruiz

IT Systems Director

Frederick Primary Care Associates, P.A.

610 Solarex Court Frederick, MD 21703

P: 301.663.6162 x2024

 <http://www.fpca.net/> http://www.fpca.net

**Comment by ilyakonovalenko** [comment]
Do you mean you respond from email? If so, there is a module Email commands which allows you to change status, assignee and some other stuff.

Anyway, you can set Default Assignee to Anyone to leave conversations unassigned when responding.

**Comment by flikamasha89** [comment]
Same issue here but is there a way to have the Default Assignee set to Nobody. Issue I am having is when someone replies to a ticket via email instead of using the webgui it automatically makes them the ticket owner but if its replied to via webgui it stays unassigned.

![image](https://user-images.githubusercontent.com/107263416/185182582-53ca2009-b725-404a-9f15-3120824292c1.png)
