### ISSUE TITLE
Unable to fetch IMAP folders from Exchange Online using OAuth

### ISSUE THREAD

**Issue by salimnassim** [freescout-helpdesk/freescout#2264]
We're having issues with fetching IMAP folders from a Exchange Online mailbox.

The mailbox is a regular user and not a shared mailbox, and it has a valid Exchange license.

OAuth has been configured correctly according to https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth and the auth flow works.

When I try to retrieve IMAP folders I get the following message "Connected, but no IMAP folders found" and IMAP folders field will be populated with the default "INBOX". Clicking "check connection" after saving displays the following error "Could not get mailbox folder: INBOX". Due to this problem emails wont be retrieved from the mailbox.

App version is 1.8.26 and the system status page does not display any errors.

Any ideas? Thanks

**Comment by freescout-helpdesk** [comment]
It looks like something is going on in MS365 system. Some people are receiving ["connection setup failed"](https://github.com/Webklex/php-imap/issues/81#issuecomment-1254558549) error. You can't get IMAP folders...

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/issues/2248 https://github.com/freescout-helpdesk/freescout/issues/2232

**Comment by freescout-helpdesk** [comment]
What happens when you click "Check Connection" button in your mailbox?

**Comment by freescout-helpdesk** [comment]
@salimnassim Does the MSD365 user you are using to connect have a mailbox in MS365 and able to access it's email at https://outlook.office365.com/mail/ ?

**Comment by salimnassim** [comment]
> What happens when you click "Check Connection" button in your mailbox?

I get a red popup notification which says "Could not get mailbox folder: INBOX"

> @salimnassim Does the MS365 user you are using to connect have a mailbox in MS365 and a license allowing to access it (try to open https://outlook.office365.com/mail/)?

The user account has a working mailbox and I can access it directly through the PWA and Outlook.

**Comment by freescout-helpdesk** [comment]
Try to contact MS365 support and ask why INBOX folder is not available via OAuth IMAP. Maybe they added some restrictions...

**Comment by salimnassim** [comment]
> Try to contact MS365 support and ask why INBOX folder is not available via OAuth IMAP. Maybe they added some restrictions...

I have created a ticket for Microsoft regarding this issue. I will update this ticket in case they have a solution.

**Comment by freescout-helpdesk** [comment]
Thanks for sharing the info.

**Comment by freescout-helpdesk** [comment]
We've added a notice to https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#fetching-emails

**Comment by salimnassim** [comment]
After Microsoft reported that the issue I referenced to is fixed the problem with retrieving folders still persists. I have tested accessing the same mailbox via IMAP using other software such as Thunderbird and it works flawlessly. Is this an issue with Webklex/php-imap perhaps? Any ideas how to debug this further? Thanks

**Comment by freescout-helpdesk** [comment]
It seems you are the only one receiving "Connected, but no IMAP folders found" error so far. You need a developer who can debug Webklex/php-imap.

**Comment by jeliasson** [comment]
> It seems you are the only one receiving "Connected, but no IMAP folders found" error so far. You need a developer who can debug Webklex/php-imap.

We also seem to have this issue where we get "Connected, but no IMAP folders found". We will continue to troubleshoot on our side, but would love some help on what that could be.

**Comment by freescout-helpdesk** [comment]
See "Debugging OAuth Emails Fetching":
https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth#debugging-oauth-emails-fetching

**Comment by pathab** [comment]
We also had connection issues to IMAP folder of all mailboxes today. All mailboxes are Microsoft 365 Exchange mailboxes. We were able to resolve the connection issues by switching the connections to OAuth. Thanks for the instructions! (https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth)

Unfortunately, after that, we were unable to retrieve IMAP folders for all mailboxes. 

The problem is that we use the SAML SSO module. So the personal account is always logged in. When we clicked "Connect", the authentication was done with the personal account and not with the account of the mailbox.
![grafik](https://user-images.githubusercontent.com/9745922/195696245-035cb966-da4d-4abf-871a-dc44e44ce194.png)


The solution to solve this problem was:
1. disconnect again
2. open Freescout in a private window in the browser
3. login as admin with the URL: yourfreescouturl.com/login?saml=0
4. connect again to the "Microsoft Exchange" under connection settings
5. authenticate with the user of the mailbox
6. done :-)

I hope this helps you.

**Comment by salimnassim** [comment]
Logging in with the mailbox user solved this issue for us, and we are able to retrieve the IMAP folders. My assumption was that the system would be smart enough to use the correct mailbox via OAuth but this was not the case.

Thanks for the workaround @pathab !

**Comment by freescout-helpdesk** [comment]
Good to know.

**Comment by PebiValeur** [comment]
I'm still experiencing this issue regarding connection setup failed.
Although there is a quick fix, where you click check connection twice.
1st time it comes with an error message "Connection setup failed"
2nd time it comes with "Connection established", and then again we are able to recieve mails for about 2 hours before it cuts the connection once more.

We are currently running an older version, due to the fact we are running it on a live enviroment.
Aswell as the fear of losing some of the settings.

Right now the version we have running is 1.8.12.
could that have anything to do with it?
Please let me know if there's anything else you need from me

thanks in advance!

**Comment by justinipg** [comment]
i'm getting an error from Microsoft saying the following.

AADSTS50011: The redirect URI 'https://servicedesk.XXX.net.au/mailbox/oauth' specified in the request does not match the redirect URIs configured for the application '288c5f41-5671-4726-9ece-XXXXXX'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

when i go to the /mailbox/oath address all i receive is a "Sorry, the page you are looking for could not be found"

**Comment by mateit-cloudware** [comment]
HI There, we have setup the Azure AD Connection to fetch mail. But are facing the following issue:
<img width="624" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/69690256/5dd5aaee-0582-4213-ba53-2477b75bba68">

We cleared the cache and also connected again. Folders where fetched perfectly all premissions are set in Azure. So still the same issue. Can you please help?

**Comment by freescout-helpdesk** [comment]
@mateit-cloudware Create a new separate issue. Also specify where and at what moment are you getting this error.

**Comment by mateit-cloudware** [comment]
@freescout-helpdesk: thank you. Done 
https://github.com/freescout-helpdesk/freescout/issues/3503
