### ISSUE TITLE
Workflow vs "Disable auto reply" - not working

### ISSUE THREAD

**Issue by palimpsestus** [freescout-helpdesk/freescout#2542]
It seems "Skip auto reply" is not working.

Settings are: Automatic, Active
Conditions: IF -- Subject -- Contains  -- New order received
Actions: Disable Auto Reply

But it is not working, it keeps sending autoreply to all the emails with "New order received" in the Subject;

I have tried different configurations, like "Body", and nothing worked.

Any idea?

Thank you

**Comment by freescout-helpdesk** [comment]
What are your FreeScout and Workflows module versions?

**Comment by freescout-helpdesk** [comment]
The issue is not confirmed with the latest FreeScout and module versions.

![2023-01-12_10-37-39](https://user-images.githubusercontent.com/40499291/212006339-dca78639-1b53-4f98-88ce-0095e2aef62e.png)

![2023-01-12_10-37-49](https://user-images.githubusercontent.com/40499291/212006358-17f51b2b-d9a6-41d0-bce0-2b48ee1dd545.png)

![2023-01-12_10-38-23](https://user-images.githubusercontent.com/40499291/212006375-f3d8361b-e161-4f66-ab37-5b172da2b5e4.png)

**Comment by palimpsestus** [comment]
Dear team, thank you for your support. It's kind of strange, because not even the message saying that workflow was trigged appears. I'm using the latest version. I'll try another tests.
