### ISSUE TITLE
Text background in incoming tickets

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#2560]
_Originally posted by @foliovision in https://github.com/freescout-helpdesk/freescout/issues/2520#issuecomment-1383808611_

              We are running into issues where some clients use **text background color** to highlight answers in their emails. This is how that looks in email notifications:

![Screen Shot 2023-01-16 at 11 09 55](https://user-images.githubusercontent.com/1180948/212652878-b4e3d14e-a90f-4114-b14a-2391a84d520d.png)

But nothing shows in Freescout:
![Screen Shot 2023-01-16 at 11 10 32](https://user-images.githubusercontent.com/1180948/212653039-c2b350c5-7a50-47bf-bb7e-990c4221346d.png)

Could the HTML filtering perhaps keep the color and background styles?

I can see the SPAN is still there:

![Screen Shot 2023-01-16 at 11 11 36](https://user-images.githubusercontent.com/1180948/212653273-6fec9917-9855-463c-aa53-15d183fdb1d3.png)

I also see the whole style attribute is **retained in database**:

`<p class="MsoNormal">I made some additional clarifications below <span style="background:yellow;mso-highlight:yellow">`

**Comment by foliovision** [comment]
I upgraded from 1.8.22 to 1.8.50 and now it works with text background color in an email I sent from gmail.com.

However in that email which I sent screenshot of it still won't work. The issue is that it uses this HTML:

`<span style="background:yellow;mso-highlight:yellow">in yellow</span>`

And the `background` CSS property is not allowed, only `background-color`: https://github.com/freescout-helpdesk/freescout/blob/dist/config/purifier.php#L29

Could you please allow both? Hopefully there would be a way of avoiding the `url()` image link if needed.

**Comment by freescout-helpdesk** [comment]
There is no easy way to allow `background` style property and prohibit to use `url()` in it. Purifier library does not provide such possibility out of the box. We'll leave this as `help wanted`.

**Comment by AlecKinnear** [comment]
Hi FreeScout,

This is causing us a lot of pain. We contribute every month, try not to nag often.

What I'd recommend FreeScout do is run a filter on the incoming HTML converting the background colour markup you don't like to markup which you do like which displays like the Gmail ones. For the purists, they can always click the Display Original button. That would be a fairly simple filter.

**Comment by AlecKinnear** [comment]
Guys, this issue is not closed. 

> What I'd recommend FreeScout do is run a filter on the incoming HTML converting the background colour markup you don't like to markup which you do like which displays like the Gmail ones. For the purists, they can always click the Display Original button. That would be a fairly simple filter.

The bandaid to send support team to view original is just that a band-aid. Improving parsing of inbound messages is important. Here it's pretty straightforward, just running a filter to convert the code which doesn't display to code which does display within FreeScout. Once you set up one of these filters you can add more of them where they are needed, ensuring that all important mark-up is visible in incoming emails.

I know you are passionate about adding new paid extensions. Improving core is also an important part of maintaining a successful open-source software project.

**Comment by freescout-helpdesk** [comment]
Replacing `background:` with `background-color:` has been implemented in FreeScout [1.8.54](https://github.com/freescout-helpdesk/freescout/releases/tag/1.8.53)
It doesn't work for you?

**Comment by foliovision** [comment]
Thank you, it works!

HTML markup from original email:

```
<p class="MsoNormal">I made some additional clarifications below <span style="background:yellow;mso-highlight:yellow">
in yellow</span>.<p>
```

Now shows in ticket as:

```
<p>I made some additional clarifications below <span style="background-color:#FFFF00;">
in yellow</span>.</p>
```

So we can see the yellow highlight used by our customers and it's good to see the MS classes and nonsense styles get stripped.

**Comment by AlecKinnear** [comment]
Thanks so much FreeScout. Small fixes like this improve workflow a great deal (not misunderstanding customer emails, not having to open everything in Display Original to double-check).
