### ISSUE TITLE
Performance Issue with Display Original

### ISSUE THREAD

**Issue by AlecKinnear** [freescout-helpdesk/freescout#2600]
While on the [topic of Display Original](https://github.com/freescout-helpdesk/freescout/issues/2560) – it can about **twenty seconds** for Display Original to work on our very powerful server which is running FreeScout. We are not running into any other performance issues. Is this normal?

PS. I've searched issues and not found any issues about Display Original performance.

@foliovision

**Comment by freescout-helpdesk** [comment]
Se \e https://github.com/freescout-helpdesk/freescout/wiki/FAQ#show-original-window-is-too-slow

**Comment by AlecKinnear** [comment]
Hi FreeScout,

We've read that FAQ of course, as one of FreeScout's most consistent supporters. I mentioned I searched issues.

Perhaps you missed my remark about "our very powerful server which is running FreeScout". FreeScout is running on powerful Linode VPS as the mail archive so it's not inter-datacenter overhead either.

I'd like to ask for your personal help troubleshooting this issue, which hopefully you can use to improve FreeScout.

**Comment by freescout-helpdesk** [comment]
The only way to find the answer is to diagnose it on your server.

**Comment by foliovision** [comment]
Freescout is using [Webklex/laravel-imap](https://github.com/Webklex/laravel-imap) to get the messages using IMAP protocol. I found that the slow component is really just the `imap_search()` call made by that library. `imap_search()` is actually a core PHP function. 

Is there no better way of doing this, like load the message by ID directly?

I see that app/Misc/Mail.php builds the IMAP search query like this:

`$query = $folder->query()->text('<'.$message_id.'>')->leaveUnread()->limit(1);`

-- https://github.com/freescout-helpdesk/freescout/blob/dist/app/Misc/Mail.php#L672

That looks like a full-text search, see https://www.php-imap.com/api/query -> "**Get all messages containing a specific text**".

Could you please use https://www.php-imap.com/api/query -> "**Get a specific message by its uid**" instead?

`$query->getMessageByUid($uid = 1);`

It seems you would have to start storing the IMAP message ID if you are not doing that already.

Note that when I use the Roundcube webmail running on our server it's very quick and loading the original message in it takes a fraction of second. So it really seems like the full-text search for the message ID is the problem here.

Thanks,
Martin

**Comment by freescout-helpdesk** [comment]
According to documentation https://github.com/Webklex/laravel-imap/tree/1.6.2#fetch-a-specific-message the `uid` is not unique and can change.

**Comment by foliovision** [comment]
The `Message-ID` field is part of the email header. Perhaps it would be faster to search in the email headers only and not do the full-text search. I found a commend to do a headers-only search in IMAP: https://www.marshallsoft.com/ImapSearch.htm

Could you please give that a try?

**Comment by freescout-helpdesk** [comment]
Extra limitation using mail date has been added to the IMAP query in the `master` branch. Check it.

**Comment by AlecKinnear** [comment]
Hi FreeScout,

That helps. Show Original now takes 600 to 700 ms on our server instead of 8 to 12 seconds. Thank you.

While we'd prefer for the search to be within headers for message ID (this would be near instant), it's unclear if header search is supported on all IMAP installs. I can see why you would not want to build the Show Original function to rely on functionality which is not part of the core PHP-IMAP library.

Searching first on date and then on text is a huge improvement. On a very busy support account it would probably be even faster to search first on date and then filter on sender and finally search text for the ID.

Our own support channels are not busy enough that it would make a huge difference.
