### ISSUE TITLE
When Deleting a user and reassigning conversations. Closed tickets are showing in assigned and unassigned folders.

### ISSUE THREAD

**Issue by dealend** [freescout-helpdesk/freescout#2660]
If you delete a user and reassign the conversations using the delete command. All closed messages are showing a closed status, but, appear in unassigned or assigned folders depending on if it was assigned anyone or someone. 

You can see the closed conversations with a lock in the screenshot.
![Screenshot_20230201_112003](https://user-images.githubusercontent.com/83796325/216101902-94ace1ea-1f8b-4f55-b654-e7519eda009a.png)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch. 

You can try to do the following:

1) Determine Closed folder ID - it's the last digit in the URL when you open the folder: _example.org/mailbox/2/12_ (12 - is the folder ID).

2) Determine Unassigned folder ID - it's the last digit in the URL when you open the folder: _example.org/mailbox/2/9_ (9 - is the folder ID).

3) Execute the following SQL in your DB (don't forget to backup your FreeScout):
```
UPDATE conversations
SET folder_id = CLOSED_FOLDER_ID
WHERE folder_id = UNASSIGNED_FOLDER_ID and `status` = 3
```
