### ISSUE TITLE
Massive delete USERS... how?

### ISSUE THREAD

**Issue by jrmaynou** [freescout-helpdesk/freescout#2805]
I have imported more than 1000 USERS from LDAP server with the LDAP module.
I have to DELETE all USERS.

Is there any way to delete them or do I have to do manually one by one?

Thank you!

**Comment by avenjamin** [comment]
@jrmaynou you may be able to do this using the API although I'm not sure you can `DELETE` a user.
It also requires you to purchase the API module.

https://api-docs.freescout.net

Otherwise you could do it directly in the database.
If you do it via the database you may need to clean up multiple tables:
- `users`
- `mailbox_users`
- `folders`
- `subscriptions`
- and maybe some others...

**Comment by avenjamin** [comment]
An alternative would be to write a console command - DeleteUser - that you could call from the command line.
Look at the CreateUser command: https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/CreateUser.php

Run it something like this
`php artisan freescout:delete-user --id=2 {--confirmDelete}`

**Comment by jrmaynou** [comment]
The command option sounds great @avenjamin because "delete database approach" seems less reliable.
Thank you!
