### ISSUE TITLE
repeated outgoing emails

### ISSUE THREAD

**Issue by DanielBendersky** [freescout-helpdesk/freescout#2858]
Hi, today I received a customer complain that he received hundreds of emails from us. Looking his screenshot we see that is true. All the emails where the same ticket number and the from was our email used for the platform free scout. We use Google as our SMTP and IMAP provider and inside the account I only found 11 emails sent. In the past 12 month, we have the same issue with 2 different customers, so this is the case number 3 that happened in 12 month. For me is very strange this behavior and don't know what can be de root source. Google? Freescout? And one else with this same issue?

Currently we are using version 1.8.69

Any advice will be grateful.

**Comment by psuter80** [comment]
in freescout, go to Manage -> Logs and check how many times you see those emails in your Outgoing Emails log. If it isn't in there hundreds of times, i doubt your problem is caused by freescout. 

also, ask your customer to send you a copy of such a message back as an attachment, so you can look at the original header of the message. this will give you some clues where the message originated from.

**Comment by DanielBendersky** [comment]
Hi, I will like to check who is the root cause of this. I used a cpanel as mail server in the first installation of free scout. After my 1st incident with many outgoing mails, I moved to Google Mail, with a paid account. That help me because Google didn’t complain me about this issue, but happened about 2 or 3 times in a timeframe of 8 months.

Last week, I got another incident and validated that in Google there was the 100 of outgoing e-mails. The account was used only for free scout, so my guess is there is a problem there. I Asked the customer the header of one of the messages, So I identified the Ticket number. In the logs  Manage -> Logs, is hard to filter to too how many mails are there, can you provide me a path where are this logs located so I can do a Shell grep to see that?

Or maybe there is a log in the database? I will like to help debuting in order to detect if there is a problem in free scout or not. If it is a problem, that debug will help to improve the system and all wins. If not, this will be a great proof that there is other problem there. That also will help other customers. So it’s a win win situation.

Please let me help on this. Just let me know where to look at.

Regards…
Daniel Bendersky

**Comment by DanielBendersky** [comment]
Hi, I found in the ticket a log where you can see the history of mail sendings from free scout:

￼

**Comment by psuter80** [comment]
Hi Daniel, your screenshot did not make it into github's issue... try to reply using github rather than sending an email reply.. maybe that helps. 

please note i'm just a user / admin of our own relatively young freescout installation trying to give some advise on how to debug and find who's causing the mail send.. so someone else needs to chime in once you can show that this is a freescout issue of some sorts. 

cheers
Pascal

**Comment by freescout-helpdesk** [comment]
Do you have CC or BCC in those emails? https://github.com/freescout-helpdesk/freescout/issues/870

**Comment by ceebee108** [comment]
We have the same Problem, see #3585
