### ISSUE TITLE
Forwarding ticket to external user creates a new ticket

### ISSUE THREAD

**Issue by bekre10** [freescout-helpdesk/freescout#2869]
Hi. I am running FreeScout 1.8.69 and realize that now, when I forward an email to an external user, it creates an additional new ticket with a new ticket number. That is not an expected / desired behavior and doesn't fulfill any practical purpose.
Instead, a comment that this ticket hast been forwarded, should remain in the same thread, not creating a new ticket and new ticket number. Is it a bug?

**Comment by psuter80** [comment]
How do you forward an email? I found two ways to forward something: 

1. Forward an entire conversation by clicking on the "..." button and then on "Forward". This will forward the entire history (at least it does that in my setup, but i have selected to always includ the history on a reply, so maybe that's why). It will indeed create a new conversation ("ticket") and it will even create a link to the new conversation in the original one, so everybody can see that the conversation was forwarded. 
2. you can forward a single message by clicking on the little down-arrow and chosing "Create New Conversation" .. i guess there is no debate there, if this action should create a new conversation or not ;) .. as far as i am concerned, it is debatable however, if that action should also create a link to the new conversation like forwarding does or not.. however,  i find it is okay the way it is now

Unless i am missing a third option here to forward a message, I think the current behavior is correct. What would you expect should happen if the recipient of the forwarded message replies, where should that reply go? and what should happen if a new message is added to the existing ticket either from internal or an external source? 

IMHO creating a new ticket and linking to it is the cleanest way to deal with this and it avoids unintended linking of possibly unrelated people over a common support case. 

Since you say the current behavior does not serve a practical purpose, here is a use case we encounter often: 
- customer creates a ticket reporting a problem with an appliance he purchased from us
- we debug with the customer to find the root cause and determine it to be a firmware bug in the OEM's firmware
- we forward the entire discussion so far to the OEM to ask for an updated Firmware to fix the bug
- OEM gets back to us with a new firmware 
- we verify internally if the firmware resolves the issue, then provide the firmware to the end customer

i the above case, I need a clear separation of the conversations i have with the OEM and our customer. Under no circumstances should our customer be bothered with our conversation with the OEM, often even happening in a different language. 

I hope that helps to clarify .. or maybe i can learn something about another forwarding method I haven't discovered yet ;) .. 
cheers
Pascal

**Comment by bekre10** [comment]
Hello Pascal. Thank you for the lengthy reply. And it makes sense for you the way it is.
It's a bit different on our end and maybe there should be an additional option / module be available for this then.

In our case, we have e.g, an info@.... address.
Sometimes, job applications send their resume to this address and some other times, customers send e.g. payment confirmations to this address. We then forward that email internally to HR or Accounting department (they are not members of the ticket system and have no access to it). There is no need to create a new ticket / ticket number for this and it could just stay within the original ticket.

If HR or Accounting did indeed then reply to such email (which is very unlikely) it used to be in the same thread.
So something must have changed with the latest release.

Bernd

**Comment by psuter80** [comment]
hi Bernd 
always interesting to hear other people's usecases :) ..
i just tried on an old 1.7.13 version i have laying around here and it behaves the same as the current version, creates a new conversation no matter which of the two methods i use..  

maybe you could work around this by creating a user for accounting and then just assign the ticket to them.. this way they get a notification which contains the original email. on your end you can simply assign and close.. haven't tested that though..

otherwise i'd convert this to a feature request or ask someone to write a module for forwarding a message the way you want. 

cheers
pascal

**Comment by bekre10** [comment]
Hello Pascal. Thanks for tryin on an older version. Strange though as I was very sure I never saw the additionally created ticket. Guess I am getting just older LOL.
Your work-around suggestion is actually quite a good idea. We use OAuth to Azure though. So if the user ever decides to login, he/she will automatically have permission to this mailbox. But since info@... is only clutter anyway, that would still be ok. So thanks a lot for your input, it was very helpful.

All the best,

Bernd

**Comment by bekre10** [comment]
@avenjamin Yes and no. If I forward an email in my email program, it doesn't create a duplicate in my Inbox. It created one in sent items. I do get the point you and the others posters mentioned. It really depends on the use case of each company. Having an option how forwarding should behave (create new thread or just make a note in the current thread that it has been forwarded) would therefore be helpful.
If the person to which we forwarded the email does reply, then yes, it should create a new ticket.
But just for the forwarded email, then no.

**Comment by freescout-helpdesk** [comment]
@bekre10 Feel free to create a feature request: https://freescout.net/request-feature/
