### ISSUE TITLE
Saved Reply not responsive 

### ISSUE THREAD

**Issue by ruess** [freescout-helpdesk/freescout#2931]
Hi there.

In Saved Replies it’s extremely difficult to use saved replies in a mobile browser or the app as the drop down gets cut off as shown in the image.

Thanks!

![994D1D8F-1740-49A6-9E9B-8DCEFAAE41C9](https://user-images.githubusercontent.com/797367/233160975-38b7c797-363e-494c-99d0-750720976a33.jpeg)

**Comment by PeopleInside** [comment]
This seems just a CSS issue.
Maybe the team need add some CSS overflow propriety.

I customized for example the Satisfaction Ratings Module because with the translation I applied was not responsive.
Just added in my case a CSS overflow set to auto https://www.w3schools.com/css/css_overflow.asp

I'm not a developer but I'm sire the team who manage the FreeScout code can fix this.
