### ISSUE TITLE
Date are not translated

### ISSUE THREAD

**Issue by bellegarde-c** [freescout-helpdesk/freescout#2950]
Date in some plugins and in main interface are not translated.

Example in base: **Apr 15** instead of **15 avril**

![image](https://user-images.githubusercontent.com/57196916/234515342-3d0f2719-1199-41af-82bd-651dd67699ed.png)

Example in Reports : **Wednesday** instead of **Mercredi**

![image](https://user-images.githubusercontent.com/57196916/234515153-24a0cf0b-7a64-4707-ae47-2cced5866a59.png)

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.

In order to see dates translated into selected language you'll need to install PHP's `intl` extension: 
```
sudo apt install php8.0-intl
```

This extension will be optional - if it's installed dates will be translated, if not - dates will be shown in English.

@tiredofit, @nebulade it would be good to add `intl` extension to FreeScout images as well.

**Comment by nebulade** [comment]
Thanks for the hint. We already have -intl installed in our app base image, so should be good.
