### ISSUE TITLE
From Name option does not work with mailbox aliases

### ISSUE THREAD

**Issue by mkduew** [freescout-helpdesk/freescout#2976]
We have a mailbox which receive messages over different aliases. For example:
- info@domain.com (main e-mail address)
- hello@domain.com 
- welcome@domain.com

I have created a mailbox in FreeScout and have set the main e-mail address from this mailbox to "info@domain.com".

Now I receive a message/ticket to welcome@domain.com - if I answer that ticket via FreeScout, automatically the "CC" field is set to "welcome@domain.com". How can I prevent this?

I've tried to set hello@domain.com and welcome@domain.com as aliases. Then the "CC" is not automatically set, but then the "From Name" setting ("User's name" is the option I have choosed) is completely ignored.

**Comment by marckemmer** [comment]
It would be nice to have a setting for using the CC field automatically or not. The problem is - if the CC field is automatically set - my own answer will be re-imported as a message in the ticket, if I forget to remove the CC receiver.

For example:
- the mailbox is set to info@domain.com and the aliases in the FreeScout mailbox are not set.
- Now I receive a message to hello@domain.com
- I answer the ticket (CC is automatically set to hello@domain.com)
- I forget to remove the CC
- now my sent answer is in the ticket and with the next mail import, my answer is now doubled.

I hope you understand the problems:
- there should be a setting, if I want to fill the CC field automatically or not (if aliases are not set)
- if I set aliases in the FreeScout mailbox and answer with an alias, the "From Name" setting is ignored.

**Comment by freescout-helpdesk** [comment]
Now mailbox From Name settings will be taken into account when sending a reply to a customer from mailbox alias.
