### ISSUE TITLE
imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com

### ISSUE THREAD

**Issue by BrianGilbert** [freescout-helpdesk/freescout#302]
Freescout v1.3.3
```
imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid; File: /www/html/overrides/Webklex/IMAP/Client.php (230) 
```
Disabling certificate validation gets around this, is that still not implemented properly?

**Comment by freescout-helpdesk** [comment]
Just disable certificate validation.

**Comment by BrianGilbert** [comment]
@freescout-helpdesk can I please get a confirmation this isn't yet implemented vs something wrong with my setup?

**Comment by freescout-helpdesk** [comment]
Are you able to fetch emails from Gmail?

**Comment by BrianGilbert** [comment]
@freescout-helpdesk only with cert validation disabled

**Comment by freescout-helpdesk** [comment]
Perfect. So enjoy. Certificate validation error happens due to your server or Gmail issues, not FreeScout.

**Comment by BrianGilbert** [comment]
So you mean that you have confirmed working cert validation against gmail on your own testing/installs?

**Comment by freescout-helpdesk** [comment]
> So you mean that you have confirmed working cert validation against gmail on your own testing/installs?

Yes.

**Comment by BrianGilbert** [comment]
thanks

**Comment by BrianGilbert** [comment]
thanks

**Comment by Sagzster** [comment]
I'm getting this exact error but I'm sure it is because our Google domain has turned off "Less Secure Apps".  Is oauth2 ever going to be an option?

**Comment by PDStig** [comment]
Hello,

I understand that this is an old issue. However, I wanted to provide some clarification that was not given in the discussion.

This issue is for self-signed certificates. But even people with other certificates, like Let's Encrypt, may get similar errors.

The issue in that case is probably PHP's IMAP extension; it does not support SIL. This has caused several people, including myself, to get similar errors in different PHP software.

See https://www.reddit.com/r/PHPhelp/comments/be0jq9/imap_gmail_ssl_no_sni_provided_please_fix_your/ .

My suggestion, if you fall into this case, is to use a third-party PHP IMAP library if possible. Disabling certificate validation is not secure, as it opens the door to SSL hijacking attacks (man-in-the-middle).

**Comment by freescout-help** [comment]
If you are connecting via IMAP (not POP3) - PHP IMAP extension is not used.

**Comment by PDStig** [comment]
I was editing my message as you replied. But I looked around and saw you're using Webklex/php-imap; that's good. I was thinking at first you were using PHP IMAP. So what I said doesn't apply to FreeScout at all. I think it's still helpful because not many are aware of the issues with PHP IMAP.
