### ISSUE TITLE
SMS Tickets Not being received by Freescout

### ISSUE THREAD

**Issue by SecureCPU** [freescout-helpdesk/freescout#3079]
I haven't been able to receive ay SMS with Twilio for some time now.

The following is the error I'm getting.
However, I check the SSL and everything seems ok. and there is nothing in the logs

Twilio was unable to fetch content from: https://desk.mywebsite.com/sms/webhook/1/xxxxxxxxxxxxxx
Error: Handshake failure
Account SID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
SID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Request ID: 33843010-e34c-4467-acc5-xxxxxxxxxxxxxxxxxxxxxxxx
Remote Host: desk.mywebsite.com
Request Method: POST
Request URI: https://desk.mywebsite.com/sms/webhook/1/5xxxxxxxxxxxx
SSL Version: TLSv1.2
URL Fragment: true

X-Twilio-Reason
Handshake failure

sourceComponent
14100

httpResponse
502

url
https://desk.mywebsite.com/sms/webhook/1/5xxxxxxxxxx

ErrorCode
11220

LogLevel
ERROR

Msg
SSL/TLS Handshake Error

EmailNotification
false

**Comment by freescout-helpdesk** [comment]
Are you using the latest FreeScout version?

**Comment by freescout-helpdesk** [comment]
Anything in Manage > Logs?

**Comment by freescout-helpdesk** [comment]
> httpResponse
> 502

Your server responds with 502 error - in such case there should be something in error logs - check all PHP and web server logs. Or there is something between your web server and browser which returns 502 error, for example CloudFlare.

Anyway the only way to find out the reason is for admin to investigate it on your server.
