### ISSUE TITLE
German - gramatical incorrectness

### ISSUE THREAD

**Issue by mokkin** [freescout-helpdesk/freescout#3083]
If a user assigns a ticket to himself for example or in general another user assigns a ticket to you, the strings are gramatically incorrect. Afaik this is not a translation error, but a programming one. In English this might not be a problem, because the correct string is always "you", but in other languages like German for example it is. The string changes between
* Sie
* Ihnen

depending on the case.

For example if I assign the ticket to myself it should be:
`Von Ihnen an Sie zugewiesen` but it is `von Sie an Sie zugewiesen`
I guess this is the corresponding string for it:
`:person assigned to :assignee`
To solve this correctly in my point of view there should be another variable like `:person_me`

Otherwise a quick an dirty fix could be to use always the users full name instead of "you", but this is not so nice of course.

![grafik](https://github.com/freescout-helpdesk/freescout/assets/2938748/e1376d8a-2ff4-4372-b1da-941097b3bd59)

**Comment by freescout-helpdesk** [comment]
Feel free to submit a pull request.

**Comment by rcknr** [comment]
There are two problems here that I can see:
1. Third person conjugation does not work for the second person (you). Example: _Sie hat dieses Gespräch weitergeleitet_ instead of _Sie haben dieses Gespräch weitergeleitet_
2. Declension of the second person pronoun (you). Example: _von Sie and Sie zugewiesen_ instead of _von Ihnen an Sie zugewiesen_.

The second problem can be addressed by replacing translations using dative case. I am not sure how to attack the first problem yet.
@mokkin Your suggestion with `:person_me` variable is already sort of implemented in the code as 'yourself' translation string. Any good examples of how this looks in other apps in German?

**Comment by cfoellmann** [comment]
I have done a lot of translation work in the WordPress space and I can say that German vs English does generate a lot of difficulties.
This particular problem is nothing I have come across particularly.

Since these status changes are some kind of log I would always use the full username even for the user himself. Result: `Max Mustermann hat dieses Gespräch weitergeleitet.`

The `Sie` (Eng: You) does not make me feel addressed at all!
I am not sure how it is for native English speakers to be displayed as You.
In these cases I would also suggest using the name and maybe a little icon or badge to make it visibly clear that you as yourself is addressed/meant.

**Comment by rcknr** [comment]
One idea I have is [to use plural form](https://laravel.com/docs/5.5/localization#pluralization) for the second person which works well for German. For example:
> :person hat dieses Gespräch weitergeleitet|:person haben dieses Gespräch weitergeleitet

**Comment by freescout-helpdesk** [comment]
If someone would like to fix this - please submit a pull request.
