### ISSUE TITLE
Whoops, looks like something went wrong — check logs in /storage/logs

### ISSUE THREAD

**Issue by jeffmatte** [freescout-helpdesk/freescout#3129]
Hello. I keep facing this error after 2FA each time. And, I'm not alone in my team. My CTO installed a fix a month ago, it didn't change anything. 

What are we supposed to do?! It's very annoying.

<img width="1440" alt="image" src="https://github.com/freescout-helpdesk/freescout/assets/120751835/c043c957-d47b-432b-bb50-206697847c68">

**Comment by freescout-helpdesk** [comment]
Have you checked /storage/logs?

**Comment by SecteurA** [comment]
Hello,

I have the same problem and when i run this command : 
```shell
php artisan config:cache 
``` 

it works but after some hours the problem comes back and when i check the logs i have this : 
[2023-06-23 05:31:01] production.ERROR: file_put_contents(/var/www/html/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/var/www/html/storage/framework/cache/data/5e/3c/5e3cbbed47195384f39edf30b47d8cd8245cdff8): Failed to open stream: Permission denied at /var/www/html/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(65): Illuminate\\Filesystem\\Filesystem->put()
#3 /var/www/html/overrides/laravel/framework/src/Illuminate/Cache/Repository.php(195): Illuminate\\Cache\\FileStore->put()
#4 /var/www/html/overrides/laravel/framework/src/Illuminate/Cache/Repository.php(327): Illuminate\\Cache\\Repository->put()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->remember()
#6 /var/www/html/overrides/nwidart/laravel-modules/src/Repository.php(239): Illuminate\\Cache\\CacheManager->__call()
#7 /var/www/html/overrides/nwidart/laravel-modules/src/Repository.php(181): Nwidart\\Modules\\Repository->getCached()
#8 /var/www/html/overrides/nwidart/laravel-modules/src/Repository.php(263): Nwidart\\Modules\\Repository->all()
#9 /var/www/html/overrides/nwidart/laravel-modules/src/Repository.php(291): Nwidart\\Modules\\Repository->getByStatus()
#10 /var/www/html/overrides/nwidart/laravel-modules/src/Repository.php(333): Nwidart\\Modules\\Repository->enabled()
#11 /var/www/html/overrides/nwidart/laravel-modules/src/Repository.php(365): Nwidart\\Modules\\Repository->getOrdered()
#12 /var/www/html/vendor/nwidart/laravel-modules/src/Providers/BootstrapServiceProvider.php(22): Nwidart\\Modules\\Repository->register()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(586): Nwidart\\Modules\\Providers\\BootstrapServiceProvider->register()
#14 /var/www/html/vendor/nwidart/laravel-modules/src/ModulesServiceProvider.php(38): Illuminate\\Foundation\\Application->register()
#15 /var/www/html/vendor/nwidart/laravel-modules/src/LaravelModulesServiceProvider.php(15): Nwidart\\Modules\\ModulesServiceProvider->registerModules()
#16 [internal function]: Nwidart\\Modules\\LaravelModulesServiceProvider->boot()
#17 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#18 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\\Container\\Container->call()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\\Foundation\\Application->bootProvider()
#23 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#29 /var/www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#30 {main}

**Comment by freescout-helpdesk** [comment]
https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by SecteurA** [comment]
Thank you for your fast reply, this is what i did : 

```shell
sudo chown -R www-data:www-data /var/www/html
ln -s /var/www/html/storage/app/public public/storage
``` 

I hope that it will be reproduced again.

Thank you
