### ISSUE TITLE
Show SMTP Queue ID in Outgoing Emails

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#3330]
In the "Outgoing Emails" pop-up for a sent reply, when the status is "Accepted for delivery", show the ID that the receiving SMTP server gave when accepting it. This makes it much easier to trace, especially on busy SMTP servers. Plus, if the SMTP ID is known, then custom code can be written that hooks into the mailserver in order to show the log entries from there.

https://github.com/freescout-helpdesk/freescout/issues/3327#issue-1878773758

**Comment by freescout-helpdesk** [comment]
https://stackoverflow.com/questions/27656923/how-to-get-email-queue-id-with-swiftmailer

**Comment by freescout-helpdesk** [comment]
It is possible to receive an SMTP Queue ID via Swiftmailer plugin:
```
250 2.0.0 Ok: queued as 6mJpz6J4RdhGh
```

But we can't determine to which `thread` this SMTP Queue ID belongs to as `Swift_Events_ResponseEvent` does not have any extra data allowing to do it:
https://github.com/freescout-helpdesk/freescout/blob/dist/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/ResponseEvent.php

**Comment by freescout-helpdesk** [comment]
@DavidAnderson684 We are trying to figure out why you may need SMTP Queue ID. Normally if a mail server can not deliver an email to the recipient it sends a bounce email containing all the details to FreeScout. Your mail server does not send bounce emails?

**Comment by DavidAnderson684** [comment]
We get bounce mails. But the cases that are more time-consuming are when the recipient doesn't see the reply for some other reason than a bounce - e.g. their spam filter silently consumed the email (far too many commercial providers do this). This results in someone having to trace the logs to see exactly whose systems lost the mail. Anything that makes this a quicker process is helpful. Without the acceptance ID showing in Freescout, someone has to read the logs and pick out the conversation via searching via non-unique fields (time, email address), so it adds inefficiency to the process (and makes it harder to automate in code).

**Comment by freescout-helpdesk** [comment]
@DavidAnderson684 Can you give an example of your SMTP Queue ID to choose proper DB field type.

**Comment by freescout-helpdesk** [comment]
Also what about `Message-ID`? Maybe it will be enough to track "logs" emails?

**Comment by DavidAnderson684** [comment]
Example of an SMTP queue ID from exim (www.exim.org - the most common SMTP server on the Internet according to http://www.securityspace.com/s_survey/data/man.201801/mxsurvey.html) is `1qdTQv-009wPw-37`. The first character is always a `1`.

The `Message-ID` is better than nothing; it's theoretically unique (though nothing guarantees this since it is client-generated and clients can't communicate with eachother), and a search on the logs can then identify lines that match it. But the queue ID is the "primary key" as far as the mailserver is concerned, and can be searched quickly especially if storing your logs in a structured format, so is much faster.

Here is an example of the log entries for an uncomplicated mail that came in an out on exim. The `Message-ID` is there, but one would have to first search for it to extract the ID the mailer has used (the one it gives as the queue ID in the SMTP conversation), and then perform a second search on that. 

```
2023-09-05 10:37:23 1qdTQv-009wPw-37 <= support@example.com H=support.example.com (support.example.com) [1.2.3.4] P=esmtpsa X=TLS1.3:TLS_AES_256_GCM_SHA384:256 CV=no A=authenticate_virtual:support@example.com S=19534 id=notify-134051-1-1693910243@example.com T="[#12345] Example.com Support Request"
2023-09-05 10:37:23 1qdTQv-009wPw-37 => support-agent-1 <contact@example.com> R=virtual_router T=dovecot_virtual_delivery_lmtp C="250 2.0.0 <support-agent-1@example.com> sJGIDeME92TPISQAj9TpAg Saved"
2023-09-05 10:37:23 1qdTQv-009wPw-37 Completed
```

**Comment by freescout-helpdesk** [comment]
Implemented in the `master` branch.
