### ISSUE TITLE
Disable "/" keyboard shortcut

### ISSUE THREAD

**Issue by sujaypawar** [freescout-helpdesk/freescout#3373]
Is there any way to disable a certain keyboard shortcut?

For example, when I press `/` key, the search bar opens up. I personally don't like that as it disturbs my flow of writing. 

How can I disable this? 

Or is there any way keyboard shortcuts could be personalized? An option for user to select their own keys for certain actions?

**Comment by freescout-helpdesk** [comment]
We'll need more details to reproduce the issue. What OS and browser are you using? Are you writing a reply or adding a note or writing something else? Can you reproduce the issue on demo.freescout.net? 

There is no way to disable/configure keyboard shortcuts.

**Comment by sumodhar** [comment]
I could see this issue on Windows 11 with Chrome or Microsoft Edge browser. We faced this issue while writing a reply and adding a note as well. 

Initially, I could recreate this issue on the FreeScout Demo website, but strangely, when I tested it again, I couldn't replicate the problem. Do you have any ideas why this happened?

Our team verified the problem on various Windows and Mac OS setups.

You can view a recording of the issue here:
Edge: [link](https://share.getcloudapp.com/d5uJlKeN)
Chrome: [link](https://www.loom.com/share/0787376533e44cb4b1e6b496f23fe723)

> Please note that we have the Keyboard Shortcuts module, and we attempted to disable it and clear the cache, but the problem persists.

**Comment by freescout-helpdesk** [comment]
Strange - this is the first time someone has this kind of issue.

What happens if you completely delete Keyboard Shortcuts module?

**Comment by sumodhar** [comment]
The issue persists with the "/" even after deleting the Keyboard Shortcuts module.

**Comment by freescout-helpdesk** [comment]
It need to be investigated on your server. Try yourself or find someone (https://github.com/freescout-helpdesk/freescout/wiki/Hire-Developer).
