### ISSUE TITLE
Wish to stop sending emails to user's email address

### ISSUE THREAD

**Issue by xpenche** [freescout-helpdesk/freescout#3772]
We have mailboxes configured for departments and users are configured to receive those.
However, we do not wish to send the emails to the individuals on their registered email addresses. 

For example, a user has has a_email@gmail.com as mail-address/username to login. All emails to their department are being sent to a_email@gmail.com too which we do not want.

What is the way to achieve this?

PHP version: 
FreeScout version: 
Database: MySQL / PostgreSQL
Are you using CloudFlare: Yes / No

**Comment by PeopleInside** [comment]
Hi, I don't know if your question is easy to understand.
When you say user's email, that are operator or customer?

Reading your request made me confused, I'm unable to understand what you want do.
If you have a department email address and email are sent to that department, email will maybe create a ticket if you configured the Help Desk to check incoming email.

Operators can decide in their profile with email notification receive.

I'm unable to understand your request :) just a personal feedback on your message.
I was just checking issues and see if I can help with some questions. I'm just a new user on this project. I discovered some day ago and installed on my personal website.

**Comment by PeopleInside** [comment]
Hum maybe its me that I am unable to understand you :-) sorry.
In my installation I have a support mail box then me as operator has a different email address.

When an email is sent to the support mailbox a ticket is created.
The email sent to the support mail box is present only on the support mailbox not in my operator email address.

I get just an alert from Freescout that notify a new ticket opened and this is because in my profile I set to be alerted when a new ticket is created.
