### ISSUE TITLE
User Mailbox

### ISSUE THREAD

**Issue by silicahd** [freescout-helpdesk/freescout#3986]
Is there a reason users cant import there mailboxes? I honestly found this system so useful that I want to also have my mailbox listed. This way all my emails can now become tickets.

**Comment by diogogpinto** [comment]
You can import your mailbox. Setup a mailbox with your email account and then go to:

`Manage > System > Tools > Fetch Emails (All)`

Keep in mind that this is a collaborative tool, is not _originally_ intended to be used as a user-personal inbox due to privacy concerns. So if you have other users using, as an admin, you would have full access to the email.

But Freescout is so flexible you can use it in any way you like, really.
