### ISSUE TITLE
Workflow Module: Post-Move Workflow results into "too many redirects"

### ISSUE THREAD

**Issue by sofl88** [freescout-helpdesk/freescout#4009]
So we tried to create a workflow that sets the status of a conversation to active after moved from one mailbox to another. The workflow is created in the target mailbox with the following conditions

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/2b450725-e97b-4d45-89c3-604140db5169)

and action

![image](https://github.com/freescout-helpdesk/freescout/assets/12407767/686f2ec1-19a6-4401-bb07-54cba4df8847)

So when someone try to move the conversation, the status is indeed set to active but the conversation stays in the same/old mailbox. Now when someone try to open this conversation, an error occurs ERR_TOO_MANY_REDIRECTS (Chrome).

Maybe I missunderstood the conditions here?

PHP version: 8.0.30
FreeScout version: 1.8.138
Database: 10.5.23-MariaDB
Are you using CloudFlare: No

Thanks in advance!

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Check errors in Manage > Logs > App Logs.

**Comment by sofl88** [comment]
Unfortunatley creating workflows is not permitted in the freescout demo (https://demo.freescout.net/). Is it possible to enable this temporary?

The logs are empty.

**Comment by freescout-helpdesk** [comment]
Unfortunately not. Try to disable all non-official modules and customizations (if any). Try to record a video of your issue.

**Comment by sofl88** [comment]
The license for official modules is exclusivly bound to one installation so we can only test this in our live system. We have indeed custom modules and customizations in our fork but fiddling around in production is no option for us.

Since you were not able to reproduce this, I assume it indeed might have something todo with our customizations / modules.

Thanks anyway.

**Comment by t-oster** [comment]
Hi, I can confirm the issue. The problem seems to be, If you first assign a new mailbox and then assign an agent, the wrong folder-id is used:

Steps:
- Create a workflow that assigns a new mailbox B and then assigns agent U
- Ticket is created via Mail for Mailbox A
- Workflow is triggered and moves Ticket to Mailbox B
- Then the workflow assigns agent U, and moves into the assigned folder of mailbox **A** (id=40/type=40 in our case), but it must be the assigned folder of mailbox **B** (id=349/type=40 in our case)
- This causes an endless redirect when trying to view that Ticket

SQL to detect broken tickets:
```SQL
SELECT c.*
FROM conversations c
         LEFT JOIN folders f ON c.folder_id = f.id AND c.mailbox_id = f.mailbox_id
WHERE f.mailbox_id IS NULL
```

If the workflow is defined the other way around (first assign agent, then mailbox) it is correctly assigned, so I suppose that the folder ID is cached in context of the source mailbox with is then wrongly used after the mailbox changed.

@sofl88 can you reopen the issue and mabye look into it?

**Comment by t-oster** [comment]
SQL to fix broken Tickets:
```SQL
UPDATE conversations c
    JOIN folders folder ON c.folder_id = folder.id AND c.mailbox_id <> folder.mailbox_id
    JOIN folders correct_folder ON correct_folder.type = folder.type AND correct_folder.mailbox_id = c.mailbox_id
SET c.folder_id = correct_folder.id
WHERE folder.id <> correct_folder.id
```

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by t-oster** [comment]
thanks, that was quick!
