### ISSUE TITLE
Not merging messages in conversation with same message-id as a reference in headers

### ISSUE THREAD

**Issue by oriolpiera** [freescout-helpdesk/freescout#4020]
PHP version: 8.3.6
FreeScout version: 1.8.138
Database: Mysql (8.0.36-28)
Are you using CloudFlare: No

The reply message that we receive in Freescout that "In-Reply-To" has another code (from de customer CRM) and the original message-id is only in "references", are not merged correctly. 
We don't know if this is a feature or a bug.

Message 1 (received to Freescout): 
Message-ID: <CAGBeX80qo1oabGM_9U3s-kbSKg-G7siyqHSSbqd9XXXXXXXXX@mail.gmail.com>

Message 2 (reply from Freescout)
Message-Id: <reply-3286-XXXXX@somenergia.coop>
References: <CAGBeX80qo1oabGM_9U3s-kbSKg-G7siyqHSSbqd9XXXXXXXXX@mail.gmail.com>
In-Reply-To: <CAGBeX80qo1oabGM_9U3s-kbSKg-G7siyqHSSbqd9XXXXXXXXX@mail.gmail.com>

Message 3 (second message to Freescout):
Message-Id: <reply-3286-XXXXX@somenergia.coop>
References: <CAGBeX80qo1oabGM_9U3s-kbSKg-G7siyqHSSbqd9XXXXXXXXX@mail.gmail.com>
In-Reply-To: <171559327604.508546.5832799601125876386.tinycrm-236947@erp-ti>

From feedback forum: https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/439478

**Comment by anxodio** [comment]
Hi! I can add some more information :)

The point is that FreeScout, as we can see [in the code](https://github.com/freescout-helpdesk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L395), tries to get the `$prev_message_id` from the `In-Reply-To` header, and if this is not set, it goes to the get the fist not empty reference in the `References` header.

But some providers as [SendGrid](https://sendgrid.com) alter a little these headers. If I reply to an email using SendGrid, it adds an strange special new ID in the stack, for example:

```
References: <reply-3291-ac86c3b74f1817a1@somenergia.coop>
 <171558990309.560360.10539124495512892944.tinycrm-236945@erp-ti>
In-Reply-To: <171558990309.560360.10539124495512892944.tinycrm-236945@erp-ti>
Message-ID: <th6C7XtDSaC0rz1nlrXICA@geopod-ismtpd-2>
```

Here, the message ID is added by SendGrid, the In-Reply-To is the original ID from the sender and the "real" In-Reply-To is the first reference.

This work with HelpScout, so I assume that them checks for the IDs of the mail in all the references to join the conversation, but FreeScout just try the "In-Reply-To" if it it's set (if I'm understanding correctly the code)

So maybe this issue is a little more complex?

**Comment by freescout-helpdesk** [comment]
You can send an email as EML file to support@freescout.net - we'll take a look.

**Comment by freescout-helpdesk** [comment]
Try with the attached /app/Console/Commands/FetchEmails.php file.

[FetchEmails.zip](https://github.com/freescout-helpdesk/freescout/files/15319275/FetchEmails.zip)

**Comment by anxodio** [comment]
I tried it :)

This solution only works for the first reply, and it's dangerous: a lot of times the In-Reply-To ID is also on the references (not only in the SendGrid case), and it can generate unexpected behaviour.

So thinking about it and doing some testing, I think the best solution is to iterate all the possibilities of reply IDs and using the first we found in our freescout threads, following the order: In-Reply-To, References (by order), special FS marker. In most cases it will work as always (getting the In-Reply-To at the first attempt), but if not, it will try the other possibilites.

I will make a PR with the code that is working correctly now in our server, let's see if I don't miss anything and it works for you :)
