### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#430]
Todo. Add to the core.

**Comment by Mte90** [comment]
Any updates? I want to migrate from opensupport because is not updated and has different issues.
Right now we are still using because has a rest api so we can script as example from a marketplace sell that automatically create an user inside the ticket system (we use webhooks with another script in the middle to wrap the 2 requests together).
The only docs I see for freescout is to create a custom module but is too much complicated for what we do now (share some parameters to a method).

**Comment by freescout-helpdesk** [comment]
https://freescout.net/module/api-webhooks/
