### ISSUE TITLE
Search, edit, merge my customers

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#452]
I would like a more advanced customer managing solution.
I now have sometimes 5x one customer. How do i merge/delete/edit in list views.

**Comment by joris85** [comment]
Here i have one customer with 3 emails. How do i get 1 customer and all the history under this customer?

**Comment by joris85** [comment]
https://www.dropbox.com/s/bpneu4myjehx51o/Schermafdruk%202020-01-27%2015.00.44.png?dl=0

**Comment by freescout-helpdesk** [comment]
It will be possible after this issue will be implemented.

**Comment by joris85** [comment]
Thanks! 
Is there a roadmap of Freescout what is accepted to add in the application?

**Comment by Marson-PL** [comment]
Oh, thanks also Joris85,

I don’t know yet but I will research this in production environment :)

Best,

Marson

**Comment by joris85** [comment]
Thanks! 

This is very important for me because i now have in notime many users that i want to migrate :-)
Do you guys also have developers for custom development, managing and helping out?

This support system is very important for us, so if it go's online i would like an emergency person.

All that i will custom develop (well my developer that i am looking for) that will be checked if it is something for in the community. If it could be useful for the community i will share it.

I work in Joomla and Wordpress so am Open Source minded, sharing is caring :-)

**Comment by freescout-helpdesk** [comment]
> Thanks!
> Is there a roadmap of Freescout what is accepted to add in the application?

https://github.com/freescout-helpdesk/freescout/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

> Do you guys also have developers for custom development, managing and helping out?

No.

**Comment by freescout-helpdesk** [comment]
Merging customers is already available. You just need to open customer profile and add edditional email addresses.

**Comment by joris85** [comment]
Hi there,

Ok i see now that you create for every email a customer.
https://www.dropbox.com/s/t3omb30szh0eka0/Schermafdruk%202020-01-28%2018.59.41.png?dl=0

This is the customer:
https://www.dropbox.com/s/zw4dmnhrjw9chjl/Schermafdruk%202020-01-28%2019.00.41.png?dl=0

You see now also 2 customers where i deleted the emails (in hopes it would disappear ;-). How do i delete these?

**Comment by freescout-helpdesk** [comment]
Impossible for now. Customers are preserved in case someone's custom module has references to them.

**Comment by floridene** [comment]
Hi there, 
did you make any changes in the regard of deleting these customers?
I want to delete "customers" after all communication mails are deleted. How can I do this? This should be possible, otherwise Art. 17 GDPR Right to erasure (‘right to be forgotten’) will be violated, right?

**Comment by freescout-helpdesk** [comment]
> Hi there,
> did you make any changes in the regard of deleting these customers?
> I want to delete "customers" after all communication mails are deleted. How can I do this? This should be possible, otherwise Art. 17 GDPR Right to erasure (‘right to be forgotten’) will be violated, right?

See https://freescout.net/module/crm/

**Comment by floridene** [comment]
We do not use the CRM (or Customer Data Enrichment module). But for every email a customer is stored. This person can still be find by searching for her/him after the conversation was deleted. How do I delete these customers? Can I deactivate the automatic generation of a customer?
![image](https://user-images.githubusercontent.com/28513956/111356986-2e475380-8689-11eb-8592-b4f298ee54d4.png)
![image](https://user-images.githubusercontent.com/28513956/111357105-48813180-8689-11eb-8a94-7f073c1a795f.png)


> > Hi there,
> > did you make any changes in the regard of deleting these customers?
> > I want to delete "customers" after all communication mails are deleted. How can I do this? This should be possible, otherwise Art. 17 GDPR Right to erasure (‘right to be forgotten’) will be violated, right?
> 
> See https://freescout.net/module/crm/

**Comment by floridene** [comment]
@freescout-helpdesk Is it just possible to delete automatically generated customers by using the CRM module?

**Comment by AlecKinnear** [comment]
Hi Floridene. There's conflicting legislation here. On one side, there's the GDPR (partly the right to be forgotten) and on the other hand, there are business requirements for keeping records of contact with customers. If this information (about interaction) is kept in a discrete system which does not share the customer's information with a visible account or with any third party services, no right to privacy is violated.

If we (FreeScout users) wish to sanitise our database by deleting customer contact information, then the easiest way to do it would be to go through the users whom you wish to delete for GDRP and just change their name and email manually. Just use a standard formula.

GDRP0001 and grdrp0001@private.com for instance.

FreeScout after consultation with lawyers (we've done these consultations, opinions conflict and are unclear) could theoretically build a GDRP purge workflow which does something similar automatically. Since legal opinions on GDRP and per company workflows vary so much, it's almost a fool's errand.

Better just to build some simple workflows of your own which remove the data you want to remove as I've outlined above.

Perhaps you could get a group of German GDRP fanatics together to:

1. solicit legal opinions and decide on what must be done to comply with GDRP and **put those guidelines in writing** for yourselves.
2. design an ideal workflow to implement those changes
3. crowdsource funding to build the custom GDRP purge module for FreeScout

I'm not joking. It's what we did. Our company have paid for some custom features which were important to us to be developed for FreeScout.
