### ISSUE TITLE
incorrect detecting of replies composed with outlook

### ISSUE THREAD

**Issue by TimoStramann** [freescout-helpdesk/freescout#461]
Hi,  
I noticed that when I get a reply from a user that was composed with outlook, freescout handels this incorrectly and also displays the message the user replied to (so typically what's displayed as outgoing in freescout directly below in the thread). The issue appears with html formatted as well as plain text replies. Additonally, the FS tag below is sometimes recongized by outlook as image and thus the whole message can get flagged.  
  
  
**plain text reply**  
![2](https://user-images.githubusercontent.com/21283057/73612563-1a5ba200-45ed-11ea-9845-18fa7fa25b0b.JPG)  
  
  
**html reply**
![1](https://user-images.githubusercontent.com/21283057/73612562-1760b180-45ed-11ea-8d30-b4a986d6da52.JPG)

**Comment by TimoStramann** [comment]
What's wrong is that freescout does not only take the message above `-- Reply above this line --` (or in German `-- Bitte oberhalb dieser Linie antworten --`) but also below that line so the whole message. If there's a long backlog, only the first few "parts" are taking but actually only the most recent answer should be displayed in freescout since all previous answers are already logged in that conversation in freescout.

**Comment by TimoStramann** [comment]
I noticed that sometimes answers composed with Thunderbird or Webclients like Roundcube get detected/displayed correctly. However, this appears to happen by chance (not really, but couldn't find a difference in client config).

**Comment by TimoStramann** [comment]
Here is the src version of the messages:

**text-only:**
![outlook-reply-textonly](https://user-images.githubusercontent.com/21283057/76618811-c2885300-6529-11ea-8b0b-8f4c4a5c8f15.JPG)

**html reply:**
![outlook-reply-html](https://user-images.githubusercontent.com/21283057/76618818-c87e3400-6529-11ea-831c-78a3f26e14a2.JPG)

**Comment by TimoStramann** [comment]
> I noticed that sometimes answers composed with Thunderbird or Webclients like Roundcube get detected/displayed correctly. However, this appears to happen by chance (not really, but couldn't find a difference in client config).

Ok, it appears that if I remove the visible, inside the email printed, Outlook email headers (like From, Subject etc.) Freescout detects the 'please reply above this line' correctly in most cases.  
Many webmail clients and Thunderbird appear to use by default "> {text}" as first character of a line to mark the quoted part of the email replying to. If the quotation is only one quote deep this doesn't cause big trouble, however, once there are multiquotes or Outlook replied we get this mess described in op.

**Comment by fvdm** [comment]
Could it be the `--` the line starts with? We had trouble with some Outlook users messing up mails. Turned out the `--` that is often used to indicate a signature caused Outlook te remove everything below and sometimes around the double dash from the mail, instead of simply hiding or styling the signature. When we removed the double dash from the signatures the problem was gone.

**Comment by TimoStramann** [comment]
@fvdm No, this didn't help. Freescout still detects the whole message as new part of the conversation. Tested a fresh Installation of Outlook 2019 on Windows 10 in a Hyper-V VM. Default settings but issue as mentioned in OP appears all time.

**Comment by joris85** [comment]
Hi there,

I also have with a couple customers the same issue.
That is sometimes a big issue and if the ticket is long we sand 50 messages with every one mail.
I send the whole conversation (lets say 6 replies) i get 7 back and that is seen as one reply. So i send those 7 replies back as the last reply and the 6 from before. 
You can imagine what i get as reply back... That is getting a big mess.
So i now use do not send reply or only the last reply as setting behind the dots (feature made by me, mostly because of this).
So i would love to see this fixed.

**Comment by TimoStramann** [comment]
I have no idea how to fix this but what I know is that other tools like zendesk or zammad have somehow solved this. There must definitively be a solution to reliably detect the messages correctly.

**Comment by joris85** [comment]
I agree, i am not a programmer otherwise i would live to investigate 🤗

Truly hope somebody can fix it. 
Helpscout also fixed this issue.

**Comment by freescout-helpdesk** [comment]
Outlook started to add `<div id="appendonsend"></div>` as reply separator (at least at outlook.live.com)

Fix is in the `master` branch. Testing is needed.
