### ISSUE TITLE
Seperate contacts per mailbox

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#466]
Hi guys,

I now would like to add a client mailbox in my freescout. 
But they can see all my contacts if i give them rights to only one mailbox, even if there are not even send one email with.

If there would be a setting to Share contacts or use contacts only from this mailbox this could be a great option to make many mailboxes.

I am PA and i manage couple businesses and i do not want that business one college can see contacts of the other business.

**Comment by freescout-helpdesk** [comment]
Won't be implemented.

**Comment by Filoz** [comment]
I'm sorry to reopen an old question.

I think that this feature could be usefull for many user. 

Can't be added as a module?

Thank you

**Comment by nooblag** [comment]
> Won't be implemented.

Any insight into why?

**Comment by joris85** [comment]
I love to know too.

for GDPR it also can be a good one to have them separated. 
Maybe in that module?

**Comment by vv221** [comment]
I have been hired to develop this feature for a non-profit organization, this will probably be done as a module and obviously distributed under a free license. Unless the Freescout team see a problem with that, I will share the module here once it has been developed and well-tested.

I can not promise a *pro bono* maintenance after the end of my contract, but I would be happy to participate in some team-shared maintenance if this module end up getting some popularity.

**Comment by nooblag** [comment]
@vv221 That's great news! Thank you!

**Comment by joris85** [comment]
Thats awesome! 
Looking forward to this module :-)

**Comment by vv221** [comment]
I started sharing my work-in-progress: https://packagist.org/packages/millions-missing-france/freescout-restricted-customers

Beware, do not try it before reading the **Disclaimer** section of that page.

If some of you would like to contribute, be it by reporting problems or by providing patches, here is the git repository where the development happens: https://port.numenaute.org/MMF/freescout-restricted-customers

**Comment by vv221** [comment]
With its version 0.8.1, I think this module is now ready to be more widely tested: https://port.numenaute.org/MMF/freescout-restricted-customers

Make sure you read the sections **Data loss warning** and **Disclaimer** before installing it on any Freescout instance including precious data. Feel free to suggest ways to reduce the impact of the module on uninstallation, and I will try to implement them.

Since it has been converted from a PHP/composer package into a Laravel/Freescout module, it is not longer available from packagist.org. The install instructions have been updated to reflect that.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/pull/4316#issuecomment-2451447975
