### ISSUE TITLE
History update, weird with the workflow message added

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#532]
So happy with the history send feature possibility :-)
Though i do like the option with design as a user gets for notification as option but that is way less important.

Here a video to show a little issue.
https://www.dropbox.com/s/ex37xit7opea0ds/history.mov?dl=0

**Comment by fvdm** [comment]
To clarify: what is going wrong according to the video, is that in the mail to the customer the reply caused by the Workflow module is added all the way to the bottom, before the initial message that started the conversation. The conversation in FreeScout has the correct order: starting at the bottom with the customer's initial message, then the Workflow response and then other replies.

_(I don't have the Workflow module myself, so I can't debug it)_

**Comment by joris85** [comment]
Well i now did not add my signature in the customize'd email so now i only have one signature.
From mister workflow  :-)

**Comment by freescout-helpdesk** [comment]
Are you still experiencing this issue? Unfortunately we can't reproduce with the latest version of FreeScout and Workflows module.

**Comment by freescout-helpdesk** [comment]
Fixed in Workflows Module v1.0.11
