### ISSUE TITLE
Fetch name from Reply-To

### ISSUE THREAD

**Issue by vlance11** [freescout-helpdesk/freescout#605]
When looking at the email box, the from name on new customers is always their email address, why is it not showing their name similar to any other email client?

**Comment by vlance11** [comment]
Turns out it works if theres not a reply to,  if the reply to email is different than the from email, it wont show the name any more (from or reply to)
.

**Comment by freescout-helpdesk** [comment]
The issue is not quite clear. Screenshots would be helpful.

**Comment by fvdm** [comment]
@freescout-helpdesk When an incoming mail only has the `To` header with a name and address, FreeScout will display the customer's name in the conversation. But when the mail also has a `Reply-To` header then FreeScout will only display the `Reply-To` address without the customer's name.

As the `Reply-To` header cannot contain a name it would be nice if FreeScout would extract the customer name from the `To` header along with the address from the `Reply-To` header.

**Comment by fvdm** [comment]
Oops, wrong wording. The name would be extracted from the `From` header instead of `To`.

**Comment by freescout-helpdesk** [comment]
We can't use name from the From header as Reply-To and From may refer to different customers.

**Comment by fvdm** [comment]
How about making it conditional? If the Reply-To header is set and it is not a customer/user then use the From name, else use the Reply-To customer's name from the database.

This is important for us because we use contact forms on our websites. We set the customer name and a static email address like _contactform@ourcompany.com_ in the From header and put their email in the Reply-To field. If we put their address in the From header it is in conflict with DKIM/DMARC as we can't sign customer domains.

**Comment by fulldecent** [comment]
This special logic seems site-specific and could lead to confusion for other people.

Recommending to close this issue and implement locally

**Comment by rilwis** [comment]
I have the same issue as @fvdm. It's a common practice to use our own email in the "From" header when people send emails through a contact form, and set their email in the "Reply-To" header.

It would be better if there's a hook to let us change this behavior.
