### ISSUE TITLE
Translate application

### ISSUE THREAD

**Issue by freescout-helpdesk** [freescout-helpdesk/freescout#62]
Now you can translate application into other languages. See [Translation guide](https://github.com/freescout-helpdesk/freescout/wiki/Translate)

**Comment by bohwaz** [comment]
OK I started translating to French :) but can't find where I can set the app to use the French language? :(

**Comment by freescout-helpdesk** [comment]
See Step 7: https://github.com/freescout-helpdesk/freescout/wiki/Translate

**Comment by bohwaz** [comment]
Yeah but I would like to see them show up in the app before I send them because I'm not sure of the context of some of the strings, so I need to check and see where they appear to make sure the translation makes sense :)

**Comment by freescout-helpdesk** [comment]
If you are a developer, try to find a way. Otherwise follow instructions.

**Comment by bohwaz** [comment]
OK then I'm gonna stop there, send the translations and wait that the language implementation is complete to finish them. Cheers.

**Comment by freescout-helpdesk** [comment]
Unfortunately we did not receive an email with the archive.
Can you archive /resources/langs folder and attach it to this ticket?

**Comment by jfparent** [comment]
[fr.zip](https://github.com/freescout-helpdesk/freescout/files/2600451/fr.zip)

small contribution

**Comment by freescout-helpdesk** [comment]
@bohwaz French language added in [FreeScout 1.0.8](https://github.com/freescout-helpdesk/freescout/releases/tag/1.0.8)

**Comment by bohwaz** [comment]
Awesome, thanks, will try to update it eventually :)

**Comment by bohwaz** [comment]
Found those translation strings that have errors:

* assigned :assignee convsersation #:conversation_number
* Remove non-npublished

**Comment by bohwaz** [comment]
I am progressing on the translation and I have a few remarks.

I would suggest including the item in the translation string and not splitting the strings as it doesn't really work in other languages.

For example: `1 total conversations |  0 active |  Viewing 1-1` appears as 3 strings in the translations: `total conversations`, `active` and `Viewing`.

But depending on the language, the number might be before, after or even inside the string.

I suggest doing instead: `:number total conversations`, `:number active` and `Viewing :current` for example.

The same issue applies to other places, for example in a conversation:

* you | marked as | Closed
* you | assigned to | anyone
* you | started the conversation

because the sentence can have a different order depending on the language you need to put full sentences in the translations, instead of just splitting the sentence like it's done actually (`you` is a separate string from `marked as`). A better solution would be:

* you marked as :new_status
* :username marked as :new_status
* you assigned to anyone
* :username assigned to anyone
* you assigned to :username
* :username assigned to :assignee_username
* you started the conversation
* :username started the conversation

Another issue is that there doesn't seem to be a way to manage plurals for strings referring to numbers. In French we have two plural forms, but singular is used for zero, in English the plural is used for zero. And in other languages it's even more complex (you can read https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html to have fun).

Thanks!

**Comment by bohwaz** [comment]
Ah yeah last small issue, special folders names like "Unassigned", "Mine" etc. cannot be translated currently.

**Comment by maxmueller89** [comment]
Hey guys, 
I just started to translate the main app into German. After a few translations I wanted to check via publish if it worked but nowhere the translation is applied. I followed the guide [Translation Guide](https://github.com/freescout-helpdesk/freescout/wiki/Translate) preciely ..

**Comment by freescout-helpdesk** [comment]
Did you choose German language in your profile?

**Comment by maxmueller89** [comment]
Lol thanks you are right. Will do a full German translation within the next two weeks and will submit it to you guys!

**Comment by maxmueller89** [comment]
I followed your Translation Guide and was able to translate everything and publish it. 

Unfortunately, when I try to share it with the button "Send Translations to Freescout Team" I get the error: **Error occured sending translations. Make sure that you have PHP Zip extension enabled and check your mail settings.**

My PHP Zip extension is enabled and my mail settings are fine as we are sending daily emails to customers. 

When clicking "Download as ZIP" I get the error: **Whoops, looks like something went wrong.** 

![Anmerkung 2019-11-26 092419](https://user-images.githubusercontent.com/6640237/69611659-91dde580-102e-11ea-9dbd-6b1f99f13c26.png)

Any idea?

**Comment by freescout-helpdesk** [comment]
Anything in System --> Logs?

**Comment by maxmueller89** [comment]
Nope
![Freescout](https://user-images.githubusercontent.com/6640237/69616953-c0ac8980-1037-11ea-8f57-b4ad4f4d9564.png)

**Comment by freescout-helpdesk** [comment]
Manage --> Logs

**Comment by maxmueller89** [comment]
Nothing unusual I guess .. 
![Freescout1](https://user-images.githubusercontent.com/6640237/69636058-0f691c00-1056-11ea-911a-2b09ee1d0291.png)
![Freescout2](https://user-images.githubusercontent.com/6640237/69636059-0f691c00-1056-11ea-91f6-6b5867fc97be.png)
![Freescout3](https://user-images.githubusercontent.com/6640237/69636061-0f691c00-1056-11ea-8870-b9d3c2202c61.png)
![Freescout4](https://user-images.githubusercontent.com/6640237/69636062-0f691c00-1056-11ea-8e59-0501695bfb52.png)

**Comment by freescout-helpdesk** [comment]
Most likely application can not create an archive in /storage/app/zipper folder due to some permissions issues. So you can archive and send `/resources/lang` folder to support@freescout.net

**Comment by globalcow** [comment]
Hi @maxmueller89, I would like to add some corrections to the German translation. I was wondering if you decided to use a formal style ("Sie") or informal ("Du")? It seems the style is a little bit mixed in the moment.

**Comment by globalcow** [comment]
Hi @freescout-helpdesk, I just worked on the German translation and fixed many things. However, als @bohwaz already said in https://github.com/freescout-helpdesk/freescout/issues/62#issuecomment-444449586, you should change the strings including 'You' and 'Yourself' as suggested by @bohwaz . Otherwise it is impossible to get a grammatically correct translated GUI in German language. 
I really love FreeScout and a good translation will be way more professional and will be definitely more appealing to new users!
