### ISSUE TITLE
How to Execute Kill Command on cPanel Shared Host

### ISSUE THREAD

**Issue by luketrip** [freescout-helpdesk/freescout#647]
My FreeScout install recently stopped fetching emails, and I checked the System Page and see error "2 commands are running at the same time. Please stop extra commands by executing the following console command"

My FreeScout install is on cPanel Shared Host (Softaculous Install) so I am not sure how to access the Console, or if this Kill command can be executed any other way???

Also, I was also hoping someone can help me understand how this happened so I can try and prevent it happening again?

I was able to Fetch the Emails using the Tools menu, but the above error still remains.

Thanks in advance for your help and advice.

![image](https://user-images.githubusercontent.com/47586638/85936537-20a53e80-b93f-11ea-8467-9343fdff0bd8.png)

**Comment by iPublicis** [comment]
If you don't have shell access (and shared hosting usually don't have) you cannot issue kill commands.
If you have just do kill -9 [the_pid_number and it would close but...

You'll have a problem again because next time the cron runs it will give you issues.

> ![image](https://user-images.githubusercontent.com/47586638/85936537-20a53e80-b93f-11ea-8467-9343fdff0bd8.png)

Just change the cron line and give more delay between fetches and it would probably solve your issue.

If not I also have a gist at  https://gist.github.com/iPublicis/7c1d7cf3f82279b17c7f31387b74112d that has a possible solution for those problems. Note that you'll need to run Exec on your PHP installation.

Can also try to add `$schedule->command('queue:work')->everyFiveMinutes()->withoutOverlapping();` to kernel.php (Laravel 5.6+) and use `php -d register_argc_argv=On`instead of `php-cli`

Hope it helps.

**Comment by iPublicis** [comment]
By the way, if you don't have the system prepared to have a personal php.ini for your user in the shared server and exec() function is disabled in server's global php.ini then you can't enable it by yourself. Sorry.

See http://php.net/manual/en/ini.core.php#ini.disable-functions

Try giving more time between fecthcing rounds and/or add the `$schedule` to kernel.php
