### ISSUE TITLE
Possible to Store Attachments Elsewhere

### ISSUE THREAD

**Issue by ManelyDave** [freescout-helpdesk/freescout#674]
Largely as a result of how our team works, our docker implementation blows away the previously running nginx+php server when we deploy to production. The database is separate and on initial startup the container does what needs to happen for it to be fairly seamless. The attachments however are in the filesystem and destroyed.
I've figured that we could have a periodic cron job store attachments onto a separate server that wouldn't be part of the build and some nginx trickery could probably serve up attachments from that. Before I got to work on it, though, I wanted to be sure there's not some magical way to already do this that you've already baked in.

You've really done a great job. I recently migrated our support team off of Salesforce and it's been super. I love what it can do out of the box and love that we've been able to add modules to do business-specific stuff.

**Comment by freescout-helpdesk** [comment]
There is no such feature for now

**Comment by alekseyp** [comment]
Using Laravel's filesystem api will open doors to using something like s3:

https://laravel.com/docs/5.5/filesystem

**Comment by freescout-helpdesk** [comment]
Yes. See https://laravel.com/docs/5.5/filesystem

**Comment by ManelyDave** [comment]
My co-worker managed to mount an AWS EFS share in the spot in the existing filesystem where Freescout expects all the files to be stored/served from, and that hack seems to be working fine. Thanks!

**Comment by mpdude** [comment]
I asked Claude Code for an assessment against Freescout 1.8.236. It said:

---
#### Where FreeScout stores attachments, and why S3 isn't a drop-in config change

**Storage today:** Attachments go through Laravel's Storage abstraction (`app/Attachment.php`), not raw file I/O — but the disk is hardcoded rather than configurable:

```php
const DISK = 'private'; // app/Attachment.php:22
```

The private disk is defined in config/filesystems.php:22-27 as the local driver, rooted at storage_path('app'). So attachments physically live under storage/app/... on the server, with no env/config knob to change that today.

Can this be switched to S3 purely via config/env? **No** — two separate gaps:

1. Missing dependency. config/filesystems.php already ships a ready-made s3 disk stanza (env-driven key/secret/region/bucket), but composer.json only requires league/flysystem core, not league/flysystem-aws-s3-v3 (the actual S3 adapter). Without it, Storage::disk('s3') throws immediately. This alone wouldn't require touching application code, just a composer require + config.
2. Several call sites require a real local filesystem path — the actual blocker.
   - Attachment::getLocalFilePath() (app/Attachment.php:337-345) calls $disk->path(...), which Flysystem throws a RuntimeException for on any non-local driver (S3 objects have no "local
     path").
   - This method is called unconditionally when sending a reply with an attachment: app/Mail/ReplyToCustomer.php:164 ($message->attach($attachment->getLocalFilePath())), and likewise when
     forwarding a conversation (app/Conversation.php:2303) and when duplicating an attachment (app/Attachment.php:451).
   - Practical impact: if private were simply repointed at s3, every outgoing reply/forward containing an attachment would fail server-side.
   - By contrast, the attachment download/view route (app/Http/Controllers/OpenController.php) is disk-agnostic and would work fine on S3 by default — unless download_attachments_via is set
     to apache/nginx (X-Sendfile/X-Accel-Redirect), which also needs a local path.
---

So, unless somebody does the design and implementation work to make the code independent of local file systems, you

* either need to mount a cloud-backed filesystem (like AWS EFS) to the directory where attachments are kept (`storage/app/attachment` probably)
* or set up some external process like `aws s3 sync ...` to replicate this directory to S3 (like a backup)

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/pull/5603
