### ISSUE TITLE
Correct way of setting up "Cron job" in Windows

### ISSUE THREAD

**Issue by fumunda** [freescout-helpdesk/freescout#709]
Thank you for an awesome program! 

I have Freescout setup and running (mostly) in IIS for server 2012 R2. Only thing I cannot figure out is how to correctly schedule the fetching of emails. I seem to have an issue with getting the `php artisan schedule:run >> /dev/null 2>&1` to work correctly.  I have tried running the command from Cygwin in the document root of Freescout and it shows as having run but the System menu does not show an updated task time.

Also the Queue:Work task never actually runs either.  I have just today spun this instance up, so I am not too worried about losing anything.  I would like to get it to work though, if you have any ideas. I just don't know what I am missing.

Anyone out there using this in IIS successfully that can point me in the right direction?

**Comment by freescout-helpdesk** [comment]
Here those who managed to install FreeScout on Windows, maybe they can give you an advice:

https://github.com/freescout-helpdesk/freescout/issues/245
https://github.com/freescout-helpdesk/freescout/issues/478

**Comment by fumunda** [comment]
Yeah I have read both of those posts. Helped me along the way but neither really explain HOW they ended up getting it to work.  I am hoping one of them will respond here and maybe give me the shove I need.

Thanks for the response though.

**Comment by fumunda** [comment]
I just went away from IIS and installed Docker for Desktop and did the container from there.  Worked like a charm.

Thanks for this wonderful product! 

 Closing this now.

**Comment by rjamesnw** [comment]
For future reference for others it works for me doing this:
1. Install cygwin (as specified in the IIS section of the installation instructions). If you don't you'll get errors with `ps` in it.
2. Make sure to add the cygwin to the PATH environment variable for the system (mine was C:\cygwin64\bin).
3. Remove the `>> /dev/null 2>&1` part. In windows the `>>` is for appending output to existing files, and since no such file exists it fails. Seems to run just fine as `php C:\inetpub\wwwroot\YOURWEBSITENAME\artisan schedule:run`.
