### ISSUE TITLE
Hook to disable updating

### ISSUE THREAD

**Issue by andrewlimaza** [freescout-helpdesk/freescout#740]
Whenever I try to update I get this error, I tried all methods except the git method. (looking into that now)

Error occured: rename(): The first argument to copy() function cannot be a directory

**Comment by andrewlimaza** [comment]
Guessing the issue is cloudron.io makes the directory read-only and doesn't allow updates and only updates through their system... :(

Closing this @freescout-helpdesk

**Comment by freescout-helpdesk** [comment]
@nebulade FYI

**Comment by nebulade** [comment]
Thanks for pulling me in here. @andrewlimaza on Cloudron the built-in update mechanism does not work, due to the read-only filesystem approach Cloudron has for the apps. We usually publish updates within a few days after upstream releases, once our end to end tests succeed for the new app package. 

I guess ideally for FreeScout on Cloudron, we would somehow hide or disable the update section in the admin panel.
@freescout-helpdesk is there maybe a way to facilitate this, to avoid further issues reported here about this problem?

Thanks

**Comment by freescout-helpdesk** [comment]
Yes. It can be done by adding `\Eventy::filter('system.can_update', true)` to the Manage > System > Status page (App Version table row).

In your module you will need to do:
```
        \Eventy::addFilter('system.can_update', function($value) {
            return false;
        });
```

**Comment by nebulade** [comment]
Thanks for the quick reply. Currently we do not have patched the code in the package anymore, nor do we have a Cloudron specific module. Is there any other way, for example through some db record, to filter/disable such events?

Otherwise it looks like those modules are regular laravel modules, however it would be the first time for me to touch that. Do you have a link to a more or less empty modules, where I can probably just add the mentioned code for the `addFilter()` call?
After that I assume following https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules#3-installing-custom-modules in the app package code will suffice?

**Comment by freescout-helpdesk** [comment]
It can be also achieved by adding `APP_DISABLE_UPDATING=false` to the .env and /config/app.php and checking it in Manage > System > Status:
```
@if (!config('app.disable_updating'))
...
@endif
```

**Comment by nebulade** [comment]
That is interesting, so there is some magic mapping from `APP_DISABLE_UPDATING` to a config flag at `app.disable_updating`? Is this a generic laravel feature? In either case, would it make sense for me to provide a pull request for the if condition in the main code instead of trying to keep a patch maintained on our side?

**Comment by freescout-helpdesk** [comment]
You will need to add to /config/app.php:

```
'disable_updating' => env('APP_DISABLE_UPDATING', false),
```

Feel free to submit a pull request.

**Comment by nebulade** [comment]
Created the pull request for this at https://github.com/freescout-helpdesk/freescout/pull/760

**Comment by nebulade** [comment]
This is now resolved, since the PR was merged. Thanks a lot!
