### ISSUE TITLE
Not automatically fetching emails - proc_open

### ISSUE THREAD

**Issue by bman955** [freescout-helpdesk/freescout#771]
I am just getting the system setup for my business but I can't seem to get emails to fetch automatically. They fetch properly when I trigger the fetch manually.

The outbound queue is working, however at first the Cron task for the queue wasn't working, I was able to get it started manually.

I have also noticed the time on Freescout is wrong even though the timezone is correct.

I seem to be experiencing the same thing as #545

**Comment by toxpal** [comment]
For fetching mails, try running cronjob manually and see if it runs properly. Also I noticed that fetching emails will not work if your server has no proc_open function enabled. Documentation doesn't list this function as required, but keep in mind it's actually required.

Regarding timezone: freescout doesn't support daylight saving time, so you will need to re-adjust timezone manually. For example, if you live in GMT+2, you will need to use GMT+3 now because of daylight saving time. Hopefully it will be implemented in future releases.

**Comment by bman955** [comment]
Interesting. Unfortunately none of the hosts I work with support enabling that feature. I should clarify that manual refreshes do in fact work as intended.

**Comment by toxpal** [comment]
Yes, this is strange behavior. I also noticed that fetching emails manually via admin dashboard works fine when proc_open is disabled, but cronjob generates error if proc_open is disabled. Maybe cronjob executes some further commands and that's why it fails without proc_open.

**Comment by freescout-helpdesk** [comment]
Make sure that you have the same PHP in the console and in the browser.

**Comment by toxpal** [comment]
That's a good point.

Is there any chance to fetch emails without using proc_open? I personally have full root access, so it's not that hard for me to enable it, but like many users mentioned, it's disabled on 99% of shared hosting providers and very few of them are willing to enable proc_open due to security reasons.

I know it's doable (since other open-source systems like osticket or uvdesk don't use proc_open for fetching), but I guess it might require lots of rewriting in your end?

**Comment by bman955** [comment]
> That's a good point.
> 
> Is there any chance to fetch emails without using proc_open? I personally have full root access, so it's not that hard for me to enable it, but like many users mentioned, it's disabled on 99% of shared hosting providers and very few of them are willing to enable proc_open due to security reasons.
> 
> I know it's doable (since other open-source systems like osticket or uvdesk don't use proc_open for fetching), but I guess it might require lots of rewriting in your end?

Yeah that would be really nice, this issue is preventing me from implementing freescout, and would also prevent me from recommending it to clients on shared hosting.

**Comment by diguinho2018** [comment]
Some hosts request the php cron job to be used like that:
`/usr/local/bin/php /XXXXX/XXXXX/public_html/helpdesk/artisan schedule:run >/dev/null 2>&1`
or
`/usr/local/bin/ea-php99 /XXXXX/XXXXX/public_html/helpdesk/artisan schedule:run >/dev/null 2>&1`

Where ea-php99 is the version of php script running on your server.
Recently I had an issue with cron job not running and I started to use this line:
`/usr/local/bin/ea-php70 /XXXXX/XXXXX/public_html/helpdesk/artisan schedule:run >/dev/null 2>&1`

**Comment by freescout-helpdesk** [comment]
Here is the workaround https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#queuework-is-not-running
