### ISSUE TITLE
Required db migration for modules

### ISSUE THREAD

**Issue by nebulade** [freescout-helpdesk/freescout#773]
Hi there,

we have bought the saved replies module today and after activation FreeScout would fail with 500 https://paste.cloudron.io/etosisudib.shell

The root cause is that this table only exists after the db migration step is performed. 
Now looking at https://github.com/freescout-helpdesk/freescout/wiki/FreeScout-Modules this was not clear that this is required.

My main question is, if the db migration should be run during module activation, triggered from the UI or if this is intentional to requiring running the db migration manually? 

If this is a bug that it was not run automatically, just wanted to note that this was on an installation on Cloudron, so maybe in this case we have to fix the packaging.

Thanks!

**Comment by freescout-helpdesk** [comment]
> My main question is, if the db migration should be run during module activation, triggered from the UI or if this is intentional to requiring running the db migration manually?

DB migration is ran automatically during module activation.

**Comment by nebulade** [comment]
Given that I saw that error and checking the db not having that table, I wonder where it went wrong. Is there some test license key or so to be able to reproduce this on fresh installations?

**Comment by tiredofit** [comment]
Nebulade as identified the migrations should run immediately after the module is installed. I too have run into this in the past, more so as I am running it in a Docker environment and sometimes inject modules instead of using the module manager. Best I can say at this time is perhaps to head to the Admin Settings and re run migrations as a safe guard after installing a module.
This could be perhaps a FAQ entry for when users experience 500 errors perhaps? It's not so common so I'm not sure it should be a message within the application.

**Comment by nebulade** [comment]
I think if the migration code is supposed to be run and it does not in some cases then this bug should be ironed out instead of an FAQ entry. Hopefully we can reproduce this more easily soon, the it should be much easier to spot.

**Comment by freescout-helpdesk** [comment]
Second migration will be executed in case migration did not work in the moment the module was activated.
