### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by statepm** [freescout-helpdesk/freescout#783]
Thank you for adding this function. One thing to note is that the day and month print out for the thread but not the year. Is it possible to add the year? Also, if time could be added, that would also be very helpful. Thanks again for the great work.

**Comment by Servery** [comment]
I would like to add some ideas:

- I think ist does not make sense to print a date like "3 days ago" on a piece of paper, because this value obviously doesn't change itself... (Date and Time would be great)

- It would be great to adjust the font-size for the printed pages. Now the font-size is too big i think.
