### ISSUE TITLE
[REQUEST] Extend Customization module to cover color palette, footer contents

### ISSUE THREAD

**Issue by SFFLAB** [freescout-helpdesk/freescout#821]
The Customization module as it exists is pretty limited; you can only add a custom logo in a few areas, and the logo has to be transposed over a blue background in the top banner even if this doesn't work aesthetically or compromises legibility. Furthermore, the footer is branded as FreeScout.

I think it would be great if we had the ability to modify the 'accent color' (which is blue as standard) as well as the contents of the footer. Those two abilities would greatly expand how customizable the support desk is, and would be particularly useful in white label implementations.

**Comment by freescout-helpdesk** [comment]
Maybe footer customization will be implemented in the future releases.

**Comment by lekkerduidelijk** [comment]
@SFFLAB I've created a custom CSS module as workaround for this. We apply some extra tweaks with it (like flipping the reply icon horizontally). It's running for some time now and doesn't interfere with FreeScout updates. 
Doesn't provide for content changes though.

**Comment by SFFLAB** [comment]
@lekkerduidelijk Yep, that idea came to mind to us as well, but we decided against it as we wanted to keep our implementation vanilla just to be safe.

**Comment by lekkerduidelijk** [comment]
It's a separate folder for the module, like described in the docs. I see no possible future issues with that. It just loads a single CSS file with some modifications. But hey, each his own 😄

**Comment by freescout-helpdesk** [comment]
Changing footer text has been implemented in Customization Module 1.0.2

**Comment by AlecKinnear** [comment]
Hey FreeScout,

The customization module (which I believe we paid for) is inadequate. It only allows changing the header colour and some icons.

What happens when one adds a red header, is a theme with a red header and blue, transparent and more blue everywhere else. It really looks duff. We could go in and investigate all the CSS classes and right all our own CSS. But that seems like a huge waste of time for users, who all have to do the legwork one by one.

What's needed here are some preset palette options for all the relevant colour choices. Then after choosing a palette, anyone who wants to customise some specific colours can do so with a colour picker (or even just a hex code).

Here's what we built to allow publishers to customise our video player:

![FV Player Custom Skin](https://cdn.foliovision.com/images/2023/07/Foliovision-Player-Skin-Customization-aer.png)

There's several other skins which require much less customisation, this shows the full customisation skin.

Please reopen this request and build out the customisation module right when you have a moment.

**Comment by freescout-helpdesk** [comment]
Unfortunately we don't have plans to spend more time on this module. Maybe someone will create something more elaborate.

**Comment by AlecKinnear** [comment]
It's dishonest to have the module in the current condition at all. It is impossible to use it to customise colours as they simply don't match. Surely you can hire someone to build this properly, in particular when I've already given you the model.

**Comment by freescout-helpdesk** [comment]
@AlecKinnear Gentle reminder: https://github.com/freescout-helpdesk/freescout/blob/master/.github/ISSUE_TEMPLATE/general_help_request.md

**Comment by AlecKinnear** [comment]
Hi FreeScout. I'm not sure what part of that boilerplate applies to my request here.

If you will recall, we support the project every month. We've been very pleased that our few requests are resolved quickly and without the usual open-source bickering (we contribute to WordPress.com and occasionally come up with optimisations of a magnitude of 100x or 1000x performance improvements and it takes up to seven years of haggling to get those optimisations put into core).

**Comment by AlecKinnear** [comment]
Here is a sample of what we see when we make the header bar dark red to match our company colours. I've put bright red around the clear errors (beyond aesthetic consideration, just out and out mismatches as the whole theme is based on your medium blue).
![FreeScout-visual-issues-with-customisation](https://github.com/freescout-helpdesk/freescout/assets/107859958/20fdef6e-952d-4cce-8013-678bd1f8c879)

**Comment by AlecKinnear** [comment]
Here's another example which shows off more of the problematic colours when menus are pressed or down. No red highlighting this time.

![FreeScout-bad-colours-example-2](https://github.com/freescout-helpdesk/freescout/assets/107859958/21b10459-72a0-4a42-bb09-95fac248eb21)

**Comment by freescout-helpdesk** [comment]
We've added Header Color option in Customization & Rebranding Module v1.0.8. If this option will continue to create this kind of issues we may consider removing it.

FreeScout team does not like your bossy tone - your account has been banned (this can't be undone). Thanks.
