### ISSUE TITLE
Unable to process your update with additional mailboxes

### ISSUE THREAD

**Issue by intered** [freescout-helpdesk/freescout#826]
Hi,

I've add mailbox for 1 domain, and that is working fine. So I've added 2 other mailboxes for 2 other domains, with both I am able to send and receive messages, so fare so good. The thing is, that the 2 newly added mailboxes getting spammed (every 2 minutes 2 emails - even when doing nothing) with the following messages:

```
Unable to process your update

Your email update couldn't be processed
If you are trying to update a conversation, remember you must respond from the same email address that's on your account. To send your update, please try again and send from your account email address (the email you login with).
```

The odd thing is, the Senders name from those messages has the name of the first mailbox I've added.

Any clue?

Here are the log files: Seems that all mailboxes have to use the same sender as the email address where you login with? But how to add multiple mailboxes from different domains?

![unable](https://user-images.githubusercontent.com/16416072/96706978-92464400-1397-11eb-97cf-2210d0756553.JPG)
![unable_2](https://user-images.githubusercontent.com/16416072/96708531-a5f2aa00-1399-11eb-89e8-233743595540.JPG)
![unable_3](https://user-images.githubusercontent.com/16416072/96708533-a68b4080-1399-11eb-9a9c-396691aeb567.JPG)

**Comment by freescout-helpdesk** [comment]
Check Sent emails in your mailboxes.

**Comment by intered** [comment]
Hi, there are none emails to be send. I've updated my first post with more info

**Comment by intered** [comment]
Dont want to cheer to soon, but think I solved it by changing the email address of the administrator to domain #2, waited 5 minutes, then changed to domain #3, waited 5 minutes and then switched back to the original email address.

Bottomline, maybe a small bug?

**Comment by freescout-helpdesk** [comment]
Have you solved your issue?

**Comment by NightDPurple** [comment]
Having the same issue here.

**Comment by Quemaqua** [comment]
Just wanted to add to this for anyone who might be searching for a solution. I'm running this on a home network for personal use and to track things I consult for/fix for my wife's small company. In my case, I confirmed this error to be a simple mismatch of email addresses in the mailbox settings. I had been using the helpful Gmail "recent:" tag before the address in the POP3 settings (e.g. recent:emailname@gmail), as I was having issues getting Gmail to connect and fetch properly via POP3. Adding the "recent:" tag to the address in the SMTP settings fixed this repeated error message. I was eventually able to remove the tag from both the SMTP and POP3 settings for the mailbox when I identified the error that had made it necessary in the first place, but any mismatch at all will cause this message to be sent over and over again even if things seem to be otherwise functioning fine within FreeScout. It didn't report any job as failed, and would clear them out periodically, but every time the scheduler would run, another dozen of the errors would pop up again.
