### ISSUE TITLE
Custom folders, show only to gives an error

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#843]
Hi guys,

If i assign a custom folder to a certain user i get an error
https://www.dropbox.com/s/yank3fb0kej617w/Schermafbeelding%202020-10-29%20om%2009.52.11.png?dl=0

No internet connection.

Second i would love to assign multiple users there.

Cheers!

**Comment by freescout-helpdesk** [comment]
We can't reproduce the issue. Check on https://demo.freescout.net

**Comment by radarsymphony** [comment]
Hi @joris85 and @freescout-helpdesk,

We are experiencing the same issue. I think I found the underlying cause. 
Demo won't let me reproduce because external users aren't able to create folders, however, I am able to replicate issue reliably on our own system. 

Version: 1.7.20
Custom Folder Module version: 1.0.4

### Summary

When attempting to create multiple custom folders that are only visible to a specific user, only _one_ folder can be created per Inbox per user before duplication error. The Freescout error logs display SQL duplicate entry error for Custom Folders Module. (see below for details)

### Steps to reproduce

1. Login and navigate to an Inbox.
3. Click 'gear' icon in left-hand inbox menu.
4. Click on **Custom Folders** in left-hand menu.
5. Click **New Folder**
6. Fill out fields, specifically setting **Show Only To** to some user (e.g. "jane")
7. Click **Save** --> "`Folder Updated`"
8. Create a _second_ custom folder, using different title/tags, but set **Show Only To** to _same user_ as before. 
9. Click **Save** --> "`Error occurred. Please check your internet connection and try again`"
10. You will be unable to create a second folder only visible to user.
11. Change **Show Only To** to a different user that does not already have a Custom Folder and it saves correctly. 

### What is the current *bug* behavior?

Unable to create more than one Custom Folder visible only to any single user in a single mailbox. 

### What is the expected *correct* behavior?

Should be able to create as many custom folders only visible to specific user. 

### Relevant logs and/or screenshots

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '55-151-200' for key 'folders_mailbox_id_user_id_type_unique' (SQL: update `folders` set `user_id` = 151, `meta` = {"order":2,"name":"Change Requests","tag_id":10305,"counter":2,"status_filter":["1","2","3"],"own_only":"","icon":"road"} where `id` = 3405) {"userId":142,"email":"[redacted]","exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '55-151-200' for key 'folders_mailbox_id_user_id_type_unique' (SQL: update `folders` set `user_id` = 151, `meta` = {\"order\":2,\"name\":\"Change Requests\",\"tag_id\":10305,\"counter\":2,\"status_filter\":[\"1\",\"2\",\"3\"],\"own_only\":\"\",\"icon\":\"road\"} where `id` = 3405) at /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '55-151-200' for key 'folders_mailbox_id_user_id_type_unique' at /www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '55-151-200' for key 'folders_mailbox_id_user_id_type_unique' at /www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115) 
```

![image](https://user-images.githubusercontent.com/73671474/143097487-1d3d544f-f10f-46c9-b0e3-9ed61799ec09.png)
![image](https://user-images.githubusercontent.com/73671474/143097524-be69a9a4-ceb2-4b22-9bec-9d5c3dda3fdf.png)

### Possible fixes

The duplication error appears to be related to how the folder configurations are named and stored in database. It looks like both custom folders generate the same id `55-151-200` and the SQL database reports the error? 

@joris85 Can you confirm that this matches your case?
