### ISSUE TITLE
Workflow not triggering

### ISSUE THREAD

**Issue by superduif** [freescout-helpdesk/freescout#885]
Hi,

I have the following workflow setup

![image](https://user-images.githubusercontent.com/8034643/100236112-ebc10600-2f35-11eb-99b8-cee285d367fc.png)

But for some reason it's not firing after a day has passed.

Does this only work if a client has replied to the ticket before or will it work after I have sent an email and he does not reply before within a day?

I want to send a follow up email if someone has not replied to an user/agent response.

**Comment by diguinho2018** [comment]
Hey!
Test this config, it works for me.

![01](https://user-images.githubusercontent.com/39450586/100272432-dd74e900-2f39-11eb-9945-00232221e209.png)

**Comment by superduif** [comment]
Hey but that is for an agent that hasn't replied how do you do that for a
client that has not replied?

**Comment by freescout-helpdesk** [comment]
Try to set "1 hour" instead of "1 day" and check.

Also try to execute manually the following console command: `php artisan freescout:workflows-process`

It work fine for us:

![2020-11-26_14-32-50](https://user-images.githubusercontent.com/40499291/100346336-b7f8e580-2ff4-11eb-9387-96c861831479.png)

![2020-11-26_14-36-52](https://user-images.githubusercontent.com/40499291/100346411-de1e8580-2ff4-11eb-88bc-9cfbdcd067e1.png)

![2020-11-26_14-33-45](https://user-images.githubusercontent.com/40499291/100346423-e37bd000-2ff4-11eb-8934-7fe3bf45783d.png)

![2020-11-26_14-34-11](https://user-images.githubusercontent.com/40499291/100346437-e8408400-2ff4-11eb-82bc-927f2b23ee77.png)

**Comment by superduif** [comment]
Hi,

Tried but it seems its not working...

[image: image.png]

[image: image.png]

[image: image.png]
[image: image.png]


[image: image.png]

**Comment by freescout-helpdesk** [comment]
It looks like we can't help here.
