### ISSUE TITLE
Docker installation help

### ISSUE THREAD

**Issue by bitcoinshirt** [freescout-helpdesk/freescout#89]
I've been waiting for months for a solution like this. The email notification made my day. My skills are very limited, so please sorry for the ignorance in advance.

I've decided to go with a Docker installation. Ideally, I would love to have it on shared-hosting, but since there were not many docs for it, I decided to go with a VPS to experiment.

1. Got a Ubuntu 16.04 VPS.
2. `sudo su - `
`apt install docker.io`
`docker pull tiredofit/freescout`

All seems to be okay. But, I've no idea what to do next. I assume that now there's a freescout with demo data installed somewhere and I have to modify that data to suit my own needs?

Here's full step by step of what I did on a test VM.

https://pastebin.com/ygp9kWnf

Ideally, I would want to have freescount on my subdomain.

So how do I get from docker installation to the point of front-end web-installation of freescout?

If you can please provide me with a newbie-friendly step by step/commands, it would be much appreciated.

Thank you for creating this once again, it's something that's really needed in the space of cluttered and polluted crappy third-party solutions.

**Comment by freescout-helpdesk** [comment]
Hi,

@tiredofit is currently hosting docker image. Eventually we will prepare a detailed instruction.

Meanwhile if you are not familiar with docker probably better just to follow regular [installation guide](https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide).

**Comment by tiredofit** [comment]
Hi, Docker takes a bit of learning to get used to, and my images are built using a few methods that assume you are running a Reverse Proxy for SSL Termination.

If you wished to use the example `docker-compose.yml` file I have provided inside the repo at https://github.com/tiredofit/docker-freescout/examples you would first need to:

a) Download and setup `jwilder/nginx-proxy`
b) Download and setup `jrCS/letsencrypt-nginx-proxy-companion`
c) Create a Docker network called `nginx-proxy`
d) Start up the image via the example docker-compose file with `docker-compose up`

You are ready :)

Since the image is not official, and just built by a community member, it might be best to create issues on it's own repository. I'll consider putting together a more standard image / add more hints inside the docker-compose.yml file to make it run without a reverse proxy, however this is the recommended approach as it handles the heavy lifting for you and allows to run multiple containers on one host without mucking about with configuration files.

**Comment by bitcoinshirt** [comment]
Thank you! In that case I'll close the issue and try the manual setup.
