### ISSUE TITLE
Customer requires Firstname and eMail

### ISSUE THREAD

**Issue by nickbe** [freescout-helpdesk/freescout#899]
When I manually create an customer, then I'm forced to enter a First/Lastname and Mail Adress.
Both should be avoided, because most of the time manual tickets are for a Company rather than a person. Also there are cases where we don't want a mail adress stored for the customer because the conversation has to be routed through other means.

Can we have Customers with either "First/Lastname" or "Company" and without the need for a mail adress?
When I enter the customer on the fly in tickets then this works without any more details.

**Comment by freescout-helpdesk** [comment]
Sorry. Won't be implemented.

**Comment by nickbe** [comment]
ok guys.... I really have to ask this now.
We are willing to help here and make the system better and more usable, now that we payed for all modules.

IF we provide new features and changes to freescout... will the pull request just be ignored?
Ex: The simplest check for either First/Lastname or Company above, together with some changes 
when displaying the names will take us an hour at most.

**Comment by freescout-helpdesk** [comment]
"Company" in Customer's profile is the company where the Customer is working. It will be unexpected behavior if instead of Customer's First or Last name users will see the name of the Company where he/she is working.

You can achieve what you need by adding hooks into the code https://github.com/freescout-helpdesk/freescout/wiki/Development-Guide#actions-and-filters and using them in your custom module.

**Comment by nickbe** [comment]
Well for 50% of our customers - this would be needed, since there's no actual person but only a support/info/contact account. So maybe when entereing a company name without first/lastname, you could simply show the sender's mail account.

I'll try to improve this with/without the module. But maybe you have a better idea for this cases.
