### ISSUE TITLE
Get pictures from Gravatar

### ISSUE THREAD

**Issue by johanoloflindberg** [freescout-helpdesk/freescout#917]
Upload photos of people through the service Gravatar. 

https://en.gravatar.com/

**Comment by johanoloflindberg** [comment]
This might be useful: https://www.libravatar.org

**Comment by diguinho2018** [comment]
FreeScout have a module called "Customer Data Enrichment" (https://freescout.net/module/customer-data-enrichment/), it gets some publicly user/customer info from web, it includes gravatar.

Is this what you are looking for?

**Comment by nickbe** [comment]
This works for us and seems well placed as a module.

**Comment by centralplexus** [comment]
PLEASE don't integrate Gravatar. It's a privacy nightmare.

**Comment by nickbe** [comment]
@centralplexus: No it doesn't. First of all this is a module: Customer Data Enrichmen, not a default feature. So up to you wether you want to install this or not. Additionally the module clearly states:

"This module automatically enriches Customers’ profiles with the information publicly available on the web"

So whatever is already publicly availabe, because I'd put it there is not against any GDPR rules.

**Comment by freescout-helpdesk** [comment]
Won't be implemented in to core. Feel free to implement via custom module.

**Comment by nickbe** [comment]
@freescout-helpdesk - I don't understand the last comment. Is this a standard reply? One post above you I explained to centralplexus that this is already integrated into a module. So why would you recomment to create another? Did I miss something here?

**Comment by centralplexus** [comment]
Yes that's fine for your side of things, but not for ours. Most people don't realise that this has privacy implications in regards to the staff using the system and internal privacy policies so why taint a perfectly good plugin with such an avoidable risk?
