### ISSUE TITLE
Move tags on list view below subject

### ISSUE THREAD

**Issue by fvdm** [freescout-helpdesk/freescout#928]
Currently when you have three or more tags on a conversation they push the subject line out of view on mobile screens. The subject line is important but the message preview below it is less important.

![image](https://user-images.githubusercontent.com/93784/102025926-3bf3f100-3d9b-11eb-942a-2201ff1ded99.jpeg)

It would be cleaner if the tags appear on the preview line below the subject.

**Comment by fvdm** [comment]
It's worse on a tablet, completely removing the subject.

![image](https://user-images.githubusercontent.com/93784/102085920-8fa42000-3e17-11eb-8548-9aff977aa26c.jpeg)

**Comment by nickbe** [comment]
I have seen the same problem here. I would also suggest to simply put it in the second line - similar to when I open the ticket. Then the tags are already below the subject.

**Comment by fvdm** [comment]
I tried doing it myself but there is no hook similar to `before_subject` to move the tags to `conv-preview`.

**Comment by nickbe** [comment]
I already implemented a new hook and it's basically a very simple patch. The problem is that this will also change narrow mobile views and that some more work has to be done to make sure it'll look pleasing on all devices.

It's on my list of supporting additions to support freescout. As soon as it's working I'll add the changes as a pull request.
