### ISSUE TITLE
Fix saving outgoing emails via IMAP

### ISSUE THREAD

**Issue by jessyvinueza** [freescout-helpdesk/freescout#984]
Your help please, after the update to system version 1.6.12, when answering a ticket from the platform, the client receives the same answer 200 or 300 emails:
The problem is that an error is generated when sending and it is sent again. Although it was sent successfully:

![Correosduplicados](https://user-images.githubusercontent.com/48226748/103912877-d82cc180-50d5-11eb-895b-1d9279bc208c.png)

**Comment by freescout-helpdesk** [comment]
Anything in Manage > System?

**Comment by jessyvinueza** [comment]
Post queue and jobs with errors are generated. And it doesn't change queue:work
![image](https://user-images.githubusercontent.com/48226748/103923458-23999c80-50e3-11eb-85fd-8c8f0507f057.png)

Functions are working

![image](https://user-images.githubusercontent.com/48226748/103923696-66f40b00-50e3-11eb-8981-cf160a998ce3.png)

And Logs > App Logs 
[laravel-2021-01-07.log](https://github.com/freescout-helpdesk/freescout/files/5783053/laravel-2021-01-07.log)

**Comment by freescout-helpdesk** [comment]
Any hanging background jobs in Manage > Status?

**Comment by jessyvinueza** [comment]
Although the mail queue is cleared, it is rebuilt with attempts that exceed 100.

We had to stop providing the service of the platform since each reply that is made arrives like 200 emails.

**Comment by jessyvinueza** [comment]
This is how queued jobs are generated, until the same response reaches the client more than a hundred times
![image](https://user-images.githubusercontent.com/48226748/104238731-6c28c100-5427-11eb-9ff2-749d4b4d8c47.png)


Customer response:

![image](https://user-images.githubusercontent.com/48226748/104239031-d93c5680-5427-11eb-805e-dfeb8d272bf6.png)


Then the queued jobs are at 0
![image](https://user-images.githubusercontent.com/48226748/104239126-ff61f680-5427-11eb-8dab-ee5e3ef5b37d.png)


And the shipping error logs are left in error, the mailbox is working correctly since the password is valid and the emails arrive:
![image](https://user-images.githubusercontent.com/48226748/104239262-3afcc080-5428-11eb-8db1-695d9f4dc72c.png)

**Comment by freescout-helpdesk** [comment]
It looks like somehow your mail server is accepting the email but returns an error.
Which mail service are you using?

**Comment by jessyvinueza** [comment]
We use the rackspace mail server. As I was telling you, you hadn't had any kind of problems, we have even acquired several modules, the problem has been presented to us when we update to the latest version.

**Comment by jessyvinueza** [comment]
Change the server with SSL configuration without certificate and the error persists:

imap_open(): Couldn't open stream {secure.emailsrvr.com:993/imap/novalidate-cert/ssl}. IMAP protocol error: Authentication aborted by client.; IMAP Authentication cancelled; File: /www/html/overrides/Webklex/IMAP/Client.php (230)

**Comment by jessyvinueza** [comment]
Good evening, after several tests the error in the configuration with the SSL certificates is detected.
IMAP folder to save outgoing replies the IMAP.Sent folder had been configured and every time an email was answered, the server looks for the TLS connection and not SSL.
We eliminated the configuration leaving empty and the problem was solved but we will not have a copy of the answers.

![image](https://user-images.githubusercontent.com/48226748/104405564-44228600-552b-11eb-8055-df93a0abc777.png)

**Comment by freescout-helpdesk** [comment]
Thanks for the info. We never thought that someone would fetch emails from the Sent folder. We will add a notice to gudes.

**Comment by yyie** [comment]
Hi, I want to clarify the problem that Jessica reports. There is an option in freescout that allows to save the outgoing replies in an IMAP folder. When we activate that option freescout sends an email using the SMTP server and then opens an IMAP connection. 
We found that the error is generated in the IMAP step and thats why when we send a reply it duplicate it 200 times. 

Looking in to it a little further, we found that the error generated by freescout when it tries to save the reply is:

`Error: imap_open(): Couldn't open stream {secure.emailsrvr.com:993/imap/tls}. [CLOSED] IMAP connection broken (server response); File: /www/html/overrides/Webklex/IMAP/Client.php (230)`

However our setup uses SSL connections, but it uses a TLS connection. When we change it to a TLS connection it uses SSL, but the fetching fails. So, our understanding of the problem is when freescout tries to open a connection for saving the outgoing reply it uses the wrong settings for opening the connection. 

For us is really important to save the reply, can you help us to fix this issue? 
Thanks in advance!


![image](https://user-images.githubusercontent.com/4340483/104461503-69d87b00-557d-11eb-865c-e480bffaa3ee.png)

**Comment by yyie** [comment]
@freescout-helpdesk can you please re-open the issue? 

Thanks in advance!!

**Comment by freescout-helpdesk** [comment]
Now when saving outgoing reply to the IMAP folder fails, the system will not send multiple emails to a customer.

But we've checked when FreeScout saves an outgoing reply to the IMAP folder, it uses same settings as when fetching emails.

**Comment by yyie** [comment]
Thank you! We will check in detail the IMAP connection problem ...
